import {
  V4FrontendArtifact,
  V4FrontendInput,
} from "./contracts";
import { frontendKebab, frontendPascal } from "./name-utils";

export class V4ShellGenerator {
  generate(input: V4FrontendInput): V4FrontendArtifact[] {
    const navigation = input.domains
      .map(
        (domain) =>
          `          <a href="/${frontendKebab(domain.key)}">${frontendPascal(domain.entityName)}</a>`,
      )
      .join("\n");

    const dashboardCards = input.domains
      .map(
        (domain) => `        <article>
          <h2>${frontendPascal(domain.entityName)}</h2>
          <a href="/${frontendKebab(domain.key)}">Open module</a>
        </article>`,
      )
      .join("\n");

    const responsiveClass = input.enableResponsiveShell !== false
      ? ' className="responsive-shell"'
      : "";

    return [
      {
        relativePath: "apps/web/app/layout.tsx",
        kind: "shell",
        content: `import "./globals.css";

export const metadata = {
  title: "${input.systemName}",
  description: "Generated by AVOS Genesis Engine v4",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body${responsiveClass}>
        <aside aria-label="Primary navigation">
          <strong>${input.systemName}</strong>
          <nav>
${navigation}
          </nav>
        </aside>
        <div>{children}</div>
      </body>
    </html>
  );
}
`,
        metadata: {
          responsive: input.enableResponsiveShell !== false,
        },
      },
      {
        relativePath: "apps/web/app/page.tsx",
        kind: "dashboard",
        content: `export default function DashboardPage() {
  return (
    <main>
      <header>
        <h1>${input.systemName}</h1>
        <p>Enterprise operations dashboard.</p>
      </header>

      <section aria-label="Domain modules">
${dashboardCards}
      </section>
    </main>
  );
}
`,
        metadata: {
          dashboard: input.enableDashboard !== false,
          domains: input.domains.length,
        },
      },
      {
        relativePath: "apps/web/app/globals.css",
        kind: "config",
        content: `* {
  box-sizing: border-box;
}

body {
  margin: 0;
  font-family: Arial, sans-serif;
}

.responsive-shell {
  display: grid;
  grid-template-columns: 260px 1fr;
  min-height: 100vh;
}

aside {
  padding: 24px;
  border-right: 1px solid #ddd;
}

nav {
  display: grid;
  gap: 12px;
  margin-top: 24px;
}

main {
  padding: 32px;
}

table {
  width: 100%;
  border-collapse: collapse;
}

th,
td {
  padding: 10px;
  border-bottom: 1px solid #ddd;
  text-align: left;
}

form {
  display: grid;
  gap: 12px;
  margin-bottom: 24px;
}

@media (max-width: 800px) {
  .responsive-shell {
    grid-template-columns: 1fr;
  }

  aside {
    border-right: 0;
    border-bottom: 1px solid #ddd;
  }
}
`,
        metadata: { responsive: true },
      },
    ];
  }
}
