import { ArtifactFactory } from "./artifact-factory";
import {
  ExecutionArtifactKind,
  GeneratedArtifact,
} from "./contracts";
import { toKebabCase, toPascalCase } from "./name-utils";

export interface ExecutableSystemBlueprint {
  systemKey: string;
  systemName: string;
  architectureStyle: string;
  modules: Array<{
    key: string;
    responsibilities: string[];
    dependencies: string[];
  }>;
  validationGates: string[];
  documentationPlan: string[];
  brainRegistrations: string[];
  evolutionRegistrations: string[];
}

export class SystemSourceGenerator {
  constructor(readonly factory = new ArtifactFactory()) {}

  generate(blueprint: ExecutableSystemBlueprint): GeneratedArtifact[] {
    const slug = toKebabCase(blueprint.systemName);
    const pascal = toPascalCase(blueprint.systemName);

    const rootIndex = this.factory.create(
      ExecutionArtifactKind.MODULE,
      "src/index.ts",
      blueprint.modules
        .map((module) => `export * from "./${toKebabCase(module.key)}";`)
        .join("\n"),
      {
        systemKey: blueprint.systemKey,
        architectureStyle: blueprint.architectureStyle,
      },
    );

    const config = this.factory.create(
      ExecutionArtifactKind.CONFIGURATION,
      "genesis.system.json",
      JSON.stringify(
        {
          systemKey: blueprint.systemKey,
          systemName: blueprint.systemName,
          slug,
          architectureStyle: blueprint.architectureStyle,
          modules: blueprint.modules.map((module) => module.key),
          validationGates: blueprint.validationGates,
        },
        null,
        2,
      ),
      {
        systemKey: blueprint.systemKey,
      },
    );

    const readme = this.factory.create(
      ExecutionArtifactKind.DOCUMENTATION,
      "README.md",
      `# ${blueprint.systemName}

Generated by AVOS Genesis Engine v2 Execution Layer.

## Architecture

- Style: ${blueprint.architectureStyle}
- Modules: ${blueprint.modules.length}
- Validation gates: ${blueprint.validationGates.length}

## Modules

${blueprint.modules
  .map(
    (module) =>
      `- **${module.key}** — ${module.responsibilities.join(", ")}`,
  )
  .join("\n")}

## Generated System Class

The generated root type is \`${pascal}\`.
`,
      {
        documentationType: "system-overview",
      },
    );

    const brainRegistration = this.factory.create(
      ExecutionArtifactKind.REGISTRATION,
      "registrations/enterprise-brain.json",
      JSON.stringify(
        {
          systemKey: blueprint.systemKey,
          registrations: blueprint.brainRegistrations,
          architectureStyle: blueprint.architectureStyle,
          modules: blueprint.modules.map((module) => ({
            key: module.key,
            responsibilities: module.responsibilities,
          })),
        },
        null,
        2,
      ),
      {
        target: "enterprise-brain",
      },
    );

    const evolutionRegistration = this.factory.create(
      ExecutionArtifactKind.REGISTRATION,
      "registrations/evolution-center.json",
      JSON.stringify(
        {
          systemKey: blueprint.systemKey,
          registrations: blueprint.evolutionRegistrations,
          baseline: {
            architectureStyle: blueprint.architectureStyle,
            moduleCount: blueprint.modules.length,
            validationGateCount: blueprint.validationGates.length,
          },
        },
        null,
        2,
      ),
      {
        target: "evolution-center",
      },
    );

    return [
      rootIndex,
      config,
      readme,
      brainRegistration,
      evolutionRegistration,
    ];
  }
}
