import { Injectable } from "@nestjs/common";
import { randomUUID } from "crypto";
import { CapabilityProductionOrchestratorService } from "./capability-production-orchestrator.service";
import { CapabilityBlueprintRegistryService } from "./capability-blueprint-registry.service";
import { CapabilityProductionCertificationService } from "./capability-production-certification.service";
import { CapabilityReleasePackagerService } from "./capability-release-packager.service";

@Injectable()
export class CapabilityProductionSmokeService {
  constructor(
    private readonly orchestrator: CapabilityProductionOrchestratorService,
    private readonly blueprints: CapabilityBlueprintRegistryService,
    private readonly certificates: CapabilityProductionCertificationService,
    private readonly packages: CapabilityReleasePackagerService
  ) {}

  run() {
    const run = this.orchestrator.run(
      {
        name: "FactoryGeneratedCapability",
        version: "1.0.0",
        description: "Capability generated by AVOS Factory Capability Production Layer.",
        domain: "factory",
        owners: ["human:khalifa"],
        dependencies: ["AVOS Factory Core V1"],
        contracts: ["execute", "health", "diagnostics"],
        qualityTargets: {
          minimumScore: 100,
          requireHumanApproval: true
        }
      },
      "human:khalifa"
    );

    const checks = {
      blueprintCreated: this.blueprints.list().length > 0,
      capabilityGenerated: run.artifactIds.length === 3,
      governanceValidated: Boolean(run.governanceReportId),
      humanFinalAuthority: this.certificates
        .list()
        .some((item) => item.humanFinalAuthority),
      capabilityCertified: run.status === "packaged",
      releasePackaged: this.packages.list().length > 0
    };

    const passed = Object.values(checks).filter(Boolean).length;
    const score = Math.round((passed / Object.keys(checks).length) * 100);
    const blockingFindings = Object.entries(checks)
      .filter(([, value]) => !value)
      .map(([name]) => name);

    return {
      id: randomUUID(),
      success: blockingFindings.length === 0,
      score,
      checks,
      blockingFindings,
      run,
      humanFinalAuthority: true,
      generatedAt: new Date().toISOString()
    };
  }
}
