import { Injectable } from "@nestjs/common";
import { ProductFactoryRequest } from "./product-factory.contracts";

@Injectable()
export class ProductBlueprintCompilerService {
  compile(request: ProductFactoryRequest) {
    const productName = request.productName.trim();
    const version = request.version?.trim() || "1.0.0";

    return {
      productId: `product:${productName.toLowerCase().replace(/\s+/g, "-")}`,
      productName,
      productType: request.productType,
      version,
      description:
        request.description?.trim() ||
        `${productName} generated by AVOS Product Factory`,
      capabilities: [...new Set(request.capabilities)],
      channels: [...new Set(request.channels ?? ["api"])],
      blueprint: {
        foundationFirst: true,
        capabilityFirst: true,
        blueprintDriven: true,
        humanFinalAuthority: true,
        ...(request.blueprint ?? {})
      },
      score: 100
    };
  }
}
