import { Injectable, NotFoundException } from "@nestjs/common";
import type { AutonomousAction } from "./core-flow-autonomy.types";
import { CoreFlowAutonomyPolicyService } from "./core-flow-autonomy-policy.service";
import { CoreFlowApprovalService } from "./core-flow-approval.service";
import { CoreFlowAuditService } from "./core-flow-audit.service";
import { CoreFlowSnapshotService } from "./core-flow-snapshot.service";

@Injectable()
export class CoreFlowAutonomyService {
  private readonly actions = new Map<string, AutonomousAction>();

  constructor(
    private readonly policy: CoreFlowAutonomyPolicyService,
    private readonly approvals: CoreFlowApprovalService,
    private readonly audit: CoreFlowAuditService,
    private readonly snapshots: CoreFlowSnapshotService,
  ) {}

  propose(dto: any) {
    const action: AutonomousAction = {
      id: `autonomy_${Date.now()}_${Math.random().toString(36).slice(2, 8)}`,
      flow: String(dto?.flow ?? "unknown"),
      executionId: String(dto?.executionId ?? "unknown"),
      action: String(dto?.action ?? "no-op"),
      rationale: String(dto?.rationale ?? "Generated by core flow intelligence."),
      confidence: Math.min(Math.max(Number(dto?.confidence ?? 0), 0), 1),
      riskScore: Math.min(Math.max(Number(dto?.riskScore ?? 0), 0), 100),
      status: "proposed",
      createdAt: new Date().toISOString(),
    };

    this.actions.set(action.id, action);
    const decision = this.policy.evaluate(action);

    if (decision.requiresApproval) {
      this.approvals.request(action.executionId, action.id);
    } else {
      action.status = "approved";
    }

    this.audit.write(action.id, "autonomy.action.proposed", {
      flow: action.flow,
      action: action.action,
      decision,
    });
    this.snapshots.create(action.id, { ...action });
    return { action, decision };
  }

  findAll(query: any = {}) {
    return Array.from(this.actions.values())
      .filter((item) => !query.status || item.status === query.status)
      .filter((item) => !query.flow || item.flow === query.flow)
      .slice()
      .reverse();
  }

  findOne(id: string) {
    const action = this.actions.get(id);
    if (!action) throw new NotFoundException("Autonomous action not found");
    return action;
  }

  approve(id: string) {
    const action = this.findOne(id);
    action.status = "approved";
    this.audit.write(id, "autonomy.action.approved");
    this.snapshots.create(id, { ...action });
    return action;
  }

  execute(id: string) {
    const action = this.findOne(id);
    action.status = "executing";
    this.audit.write(id, "autonomy.action.executing");
    action.status = "completed";
    action.completedAt = new Date().toISOString();
    this.audit.write(id, "autonomy.action.completed");
    this.snapshots.create(id, { ...action });
    return action;
  }

  fail(id: string, error: unknown) {
    const action = this.findOne(id);
    action.status = "failed";
    action.error = error instanceof Error ? error.message : String(error);
    action.completedAt = new Date().toISOString();
    this.audit.write(id, "autonomy.action.failed", { error: action.error });
    this.snapshots.create(id, { ...action });
    return action;
  }

  rollback(id: string, reason?: string) {
    const action = this.findOne(id);
    action.status = "rolled-back";
    action.completedAt = new Date().toISOString();
    this.audit.write(id, "autonomy.action.rolled-back", { reason });
    this.snapshots.create(id, { ...action });
    return action;
  }

  dashboard() {
    const items = Array.from(this.actions.values());
    const count = (status: AutonomousAction["status"]) =>
      items.filter((item) => item.status === status).length;

    return {
      total: items.length,
      proposed: count("proposed"),
      approved: count("approved"),
      executing: count("executing"),
      completed: count("completed"),
      failed: count("failed"),
      rolledBack: count("rolled-back"),
      generatedAt: new Date().toISOString(),
    };
  }
}
