import { IndustryCode } from "./industry-mega-bundle-1.types";

export const INDUSTRY_CAPABILITIES: Record<IndustryCode, string[]> = {
  HEALTHCARE: [
    "patient-registry",
    "appointments",
    "clinical-operations",
    "care-plans",
    "pharmacy",
    "laboratory",
    "billing",
    "insurance-claims",
    "clinical-ai",
    "compliance",
  ],
  CONSTRUCTION: [
    "projects",
    "sites",
    "contracts",
    "cost-control",
    "workforce",
    "equipment",
    "materials",
    "safety",
    "progress",
    "project-ai",
  ],
  MANUFACTURING: [
    "plants",
    "production-orders",
    "bom",
    "work-centers",
    "quality",
    "maintenance",
    "inventory",
    "supply-chain",
    "oee",
    "manufacturing-ai",
  ],
  LOGISTICS_FLEET: [
    "fleet",
    "drivers",
    "routes",
    "shipments",
    "dispatch",
    "warehouses",
    "tracking",
    "fuel",
    "maintenance",
    "logistics-ai",
  ],
  REAL_ESTATE: [
    "properties",
    "units",
    "leases",
    "sales",
    "tenants",
    "maintenance",
    "facilities",
    "payments",
    "valuations",
    "real-estate-ai",
  ],
};