import { GlobalScaleCapability } from "./global-scale-ultra.types";
export const GLOBAL_SCALE_CAPABILITIES: Record<GlobalScaleCapability,{name:string;category:string}> = {
  GLOBAL_EXPANSION:{name:"Global Expansion Engine",category:"EXPANSION"},
  REGIONAL_OPERATIONS:{name:"Regional Operations",category:"OPERATIONS"},
  MULTI_REGION_ORCHESTRATION:{name:"Multi-Region Orchestration",category:"PLATFORM"},
  COUNTRY_LAUNCH_FACTORY:{name:"Country Launch Factory",category:"EXPANSION"},
  LOCALIZATION_OPERATIONS:{name:"Localization Operations",category:"LOCALIZATION"},
  CURRENCY_TAX_CONFIGURATION:{name:"Currency & Tax Configuration",category:"FINANCE"},
  REGULATORY_LOCALIZATION:{name:"Regulatory Localization",category:"COMPLIANCE"},
  PARTNER_ECOSYSTEM:{name:"Partner Ecosystem",category:"PARTNERS"},
  STRATEGIC_ALLIANCES:{name:"Strategic Alliances",category:"PARTNERS"},
  FRANCHISE_NETWORK:{name:"Franchise Network",category:"NETWORK"},
  DISTRIBUTOR_NETWORK:{name:"Distributor Network",category:"NETWORK"},
  SUPPLIER_NETWORK:{name:"Supplier Network",category:"NETWORK"},
  GLOBAL_VENDOR_MANAGEMENT:{name:"Global Vendor Management",category:"VENDOR"},
  CROSS_BORDER_COMMERCE:{name:"Cross-Border Commerce",category:"COMMERCE"},
  GLOBAL_PAYMENTS:{name:"Global Payments",category:"FINANCE"},
  GLOBAL_BILLING:{name:"Global Billing",category:"FINANCE"},
  GLOBAL_IDENTITY:{name:"Global Identity",category:"IDENTITY"},
  DATA_RESIDENCY:{name:"Data Residency",category:"DATA"},
  SOVEREIGN_CLOUD:{name:"Sovereign Cloud",category:"PLATFORM"},
  GLOBAL_COMPLIANCE:{name:"Global Compliance",category:"COMPLIANCE"},
  BUSINESS_CONTINUITY:{name:"Business Continuity",category:"RESILIENCE"},
  ENTERPRISE_RESILIENCE:{name:"Enterprise Resilience",category:"RESILIENCE"},
  DISASTER_RECOVERY:{name:"Disaster Recovery",category:"RECOVERY"},
  GLOBAL_FAILOVER:{name:"Global Failover",category:"RECOVERY"},
  CAPACITY_PLANNING:{name:"Capacity Planning",category:"OPERATIONS"},
  RESOURCE_OPTIMIZATION:{name:"Resource Optimization",category:"EFFICIENCY"},
  SUSTAINABILITY:{name:"Sustainability Platform",category:"SUSTAINABILITY"},
  ESG_INTELLIGENCE:{name:"ESG Intelligence",category:"SUSTAINABILITY"},
  GLOBAL_OPERATIONS_CENTER:{name:"Global Operations Center",category:"CONTROL"},
  GLOBAL_SCALE_COMMAND_CENTER:{name:"Global Scale Command Center",category:"CONTROL"}
};