import { IndustryCode } from "./industry-mega-bundle-2.types";

export const INDUSTRY_CAPABILITIES: Record<IndustryCode, string[]> = {
  AVIATION: [
    "aircraft-registry",
    "flight-operations",
    "crew-management",
    "maintenance",
    "ground-operations",
    "airport-services",
    "safety",
    "compliance",
    "revenue-management",
    "aviation-ai",
  ],
  MARITIME: [
    "vessel-registry",
    "voyage-management",
    "port-operations",
    "crew-management",
    "cargo",
    "maintenance",
    "marine-safety",
    "customs",
    "chartering",
    "maritime-ai",
  ],
  AGRICULTURE: [
    "farm-registry",
    "field-management",
    "crop-planning",
    "livestock",
    "irrigation",
    "inventory",
    "supply-chain",
    "quality",
    "sustainability",
    "agriculture-ai",
  ],
  ENERGY_UTILITIES: [
    "asset-registry",
    "generation",
    "transmission",
    "distribution",
    "metering",
    "outages",
    "maintenance",
    "billing",
    "sustainability",
    "energy-ai",
  ],
  BANKING_FINANCE: [
    "customer-onboarding",
    "accounts",
    "payments",
    "lending",
    "treasury",
    "risk",
    "fraud",
    "compliance",
    "wealth-management",
    "banking-ai",
  ],
};