param(
    [string]$BaseUrl = "http://localhost:3000"
)

$ErrorActionPreference = "Stop"
$Root = "$BaseUrl/avos/platform/service-lifecycle"
$ServiceId = "platform-pack-1a-smoke-resource"

Write-Host "1. Status"
Invoke-RestMethod -Method Get -Uri "$Root/status" | Format-List

Write-Host "2. Start service"
$StartBody = @{
    command = "start"
    actorId = "Khalifa"
    reason = "Platform Pack 1B smoke test"
    metadata = @{
        test = $true
    }
} | ConvertTo-Json -Depth 10

try {
    Invoke-RestMethod `
        -Method Post `
        -Uri "$Root/services/$ServiceId/commands" `
        -ContentType "application/json" `
        -Body $StartBody | Format-List
}
catch {
    $Runtime = Invoke-RestMethod -Method Get -Uri "$Root/runtime/$ServiceId"
    if ($Runtime.runtime.state -ne "running") {
        throw
    }
    Write-Host "Service was already running."
}

Write-Host "3. Record healthy heartbeat"
$HeartbeatBody = @{
    status = "healthy"
    latencyMs = 12
    details = @{
        source = "pack-1b-smoke-test"
    }
} | ConvertTo-Json -Depth 10

Invoke-RestMethod `
    -Method Post `
    -Uri "$Root/services/$ServiceId/heartbeat" `
    -ContentType "application/json" `
    -Body $HeartbeatBody | Format-List

Write-Host "4. Enter maintenance"
$MaintenanceBody = @{
    command = "enter-maintenance"
    actorId = "Khalifa"
    reason = "Validate maintenance lifecycle"
} | ConvertTo-Json -Depth 10

Invoke-RestMethod `
    -Method Post `
    -Uri "$Root/services/$ServiceId/commands" `
    -ContentType "application/json" `
    -Body $MaintenanceBody | Format-List

Write-Host "5. Exit maintenance"
$ExitBody = @{
    command = "exit-maintenance"
    actorId = "Khalifa"
    reason = "Maintenance validation complete"
} | ConvertTo-Json -Depth 10

Invoke-RestMethod `
    -Method Post `
    -Uri "$Root/services/$ServiceId/commands" `
    -ContentType "application/json" `
    -Body $ExitBody | Format-List

Write-Host "6. Record warning failure"
$FailureBody = @{
    code = "PACK_1B_SMOKE_WARNING"
    message = "Synthetic warning generated by smoke test."
    severity = "warning"
    details = @{
        synthetic = $true
    }
} | ConvertTo-Json -Depth 10

$Failure = Invoke-RestMethod `
    -Method Post `
    -Uri "$Root/services/$ServiceId/failures" `
    -ContentType "application/json" `
    -Body $FailureBody

$Failure | Format-List

Write-Host "7. Recover service"
$RecoverBody = @{
    command = "recover"
    actorId = "Khalifa"
    reason = "Recover from synthetic warning"
} | ConvertTo-Json -Depth 10

Invoke-RestMethod `
    -Method Post `
    -Uri "$Root/services/$ServiceId/commands" `
    -ContentType "application/json" `
    -Body $RecoverBody | Format-List

Write-Host "8. Resolve failure"
Invoke-RestMethod `
    -Method Patch `
    -Uri "$Root/failures/$($Failure.id)/resolve" | Format-List

Write-Host "9. Diagnostics"
Invoke-RestMethod `
    -Method Get `
    -Uri "$Root/services/$ServiceId/diagnostics" | Format-List

Write-Host "10. Runtime status"
Invoke-RestMethod `
    -Method Get `
    -Uri "$Root/runtime/$ServiceId" | ConvertTo-Json -Depth 10

Write-Host "11. Command history"
Invoke-RestMethod `
    -Method Get `
    -Uri "$Root/commands?serviceId=$ServiceId&limit=20" | Format-Table command, status, fromState, toState, actorId

Write-Host "12. Health"
Invoke-RestMethod -Method Get -Uri "$Root/health" | Format-List

Write-Host "13. Final review"
Invoke-RestMethod -Method Post -Uri "$Root/final-review/run" | Format-List

Write-Host "14. Certification"
Invoke-RestMethod -Method Post -Uri "$Root/certification/certify" | Format-List