[CmdletBinding()]
param(
  [string]$RepoRoot = "C:\Users\User\Desktop\AVOS",
  [Parameter(Mandatory)][string]$ManifestPath,
  [switch]$Validate,
  [switch]$Commit,
  [switch]$Push
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"
$ProgressPreference = "SilentlyContinue"

$EngineRoot = Join-Path $PSScriptRoot "engine"
$TemplateRoot = Join-Path $PSScriptRoot "templates"

. (Join-Path $EngineRoot "common.ps1")
. (Join-Path $EngineRoot "manifest-engine.ps1")
. (Join-Path $EngineRoot "template-engine.ps1")
. (Join-Path $EngineRoot "registration-engine.ps1")
. (Join-Path $EngineRoot "build-engine.ps1")
. (Join-Path $EngineRoot "git-engine.ps1")

$RepoRoot = (Resolve-Path -LiteralPath $RepoRoot).Path
$ManifestPath = (Resolve-Path -LiteralPath $ManifestPath).Path

Assert-CleanGit -RepoRoot $RepoRoot

$manifest = Read-PackManifest -ManifestPath $ManifestPath

$moduleSlug = [string]$manifest.moduleSlug
$pascal = Convert-ToPascalCase -Value $moduleSlug

$tokens = @{
  TITLE = [string]$manifest.title
  MODULE_SLUG = $moduleSlug
  MODULE_NAME = "${pascal}Module"
  CONTROLLER_NAME = "${pascal}Controller"
  SERVICE_NAME = "${pascal}Service"
  TYPE_NAME = "${pascal}Capability"
  RECORD_NAME = "${pascal}Record"
  REGISTRY_NAME = "$($moduleSlug.Replace('-','_').ToUpperInvariant())_CAPABILITIES"
  MOBILE_CLASS = "${pascal}Screen"
}

$tokens.CAPABILITY_UNION = (
  $manifest.capabilities |
    ForEach-Object { "  | `"$_`"" }
) -join "`r`n"

$tokens.CAPABILITY_REGISTRY = (
  $manifest.capabilities |
    ForEach-Object {
      $label = ($_ -replace "_"," ").ToLowerInvariant()
      $label = (Get-Culture).TextInfo.ToTitleCase($label)
      "  $_`: `"$label`","
    }
) -join "`r`n"

$tokens.WEB_CAPABILITIES = (
  $manifest.capabilities |
    ForEach-Object {
      $label = ($_ -replace "_"," ").ToLowerInvariant()
      $label = (Get-Culture).TextInfo.ToTitleCase($label)
      "  `"$label`","
    }
) -join "`r`n"

$apiRoot = Join-Path $RepoRoot "apps/api/src/$moduleSlug"
$webRoot = Join-Path $RepoRoot "apps/web/src/app/$moduleSlug"
$mobileSlug = $moduleSlug.Replace("-","_")
$mobileRoot = Join-Path $RepoRoot "apps/mobile/lib/features/$mobileSlug"
$docsRoot = Join-Path $RepoRoot "docs/generated/$moduleSlug"
$toolsRoot = Join-Path $RepoRoot "tools/generated/$moduleSlug"

New-Item -ItemType Directory -Force -Path `
  $apiRoot,$webRoot,$mobileRoot,$docsRoot,$toolsRoot | Out-Null

$files = @(
  @{
    Template = "types.ts.tpl"
    Output = Join-Path $apiRoot "$moduleSlug.types.ts"
  },
  @{
    Template = "registry.ts.tpl"
    Output = Join-Path $apiRoot "$moduleSlug.registry.ts"
  },
  @{
    Template = "service.ts.tpl"
    Output = Join-Path $apiRoot "$moduleSlug.service.ts"
  },
  @{
    Template = "controller.ts.tpl"
    Output = Join-Path $apiRoot "$moduleSlug.controller.ts"
  },
  @{
    Template = "module.ts.tpl"
    Output = Join-Path $apiRoot "$moduleSlug.module.ts"
  },
  @{
    Template = "index.ts.tpl"
    Output = Join-Path $apiRoot "index.ts"
  },
  @{
    Template = "web-page.tsx.tpl"
    Output = Join-Path $webRoot "page.tsx"
  },
  @{
    Template = "mobile-screen.dart.tpl"
    Output = Join-Path $mobileRoot "${mobileSlug}_screen.dart"
  }
)

foreach ($file in $files) {
  $content = Expand-PackTemplate `
    -TemplatePath (Join-Path $TemplateRoot $file.Template) `
    -Tokens $tokens

  if (Test-Path -LiteralPath $file.Output) {
    throw "Output already exists: $($file.Output)"
  }

  Write-Utf8 -Path $file.Output -Content $content
  Write-Host "Created: $($file.Output)" -ForegroundColor DarkGray
}

Write-Utf8 `
  -Path (Join-Path $mobileRoot "${mobileSlug}.dart") `
  -Content "export `"${mobileSlug}_screen.dart`";`r`n"

Register-NestModule `
  -AppModulePath (Join-Path $RepoRoot "apps/api/src/app.module.ts") `
  -ModuleName $tokens.MODULE_NAME `
  -ImportPath "./$moduleSlug/$moduleSlug.module"

$manifestJson = $manifest | ConvertTo-Json -Depth 20
Write-Utf8 `
  -Path (Join-Path $docsRoot "manifest.json") `
  -Content $manifestJson

Write-Utf8 `
  -Path (Join-Path $docsRoot "README.md") `
  -Content @"
# $($manifest.title)

Generated by AVOS Pack Builder V1.

- Code: $($manifest.code)
- Module: $moduleSlug
- Capabilities: $($manifest.capabilities.Count)
- Entities: $($manifest.entities.Count)
"@

if ($Validate) {
  Invoke-PackValidation -RepoRoot $RepoRoot
}

$commitStatus = "NOT_REQUESTED"

if ($Commit) {
  $message = if ($manifest.commitMessage) {
    [string]$manifest.commitMessage
  }
  else {
    "feat(pack-builder): generate $($manifest.title)"
  }

  $commitStatus = Complete-PackGit `
    -RepoRoot $RepoRoot `
    -CommitMessage $message `
    -Push:$Push
}

[pscustomobject]@{
  success = $true
  system = "AVOS Pack Builder V1"
  generatedPack = $manifest.title
  module = $moduleSlug
  capabilities = $manifest.capabilities.Count
  validation = if ($Validate) { "PASS" } else { "SKIPPED" }
  commit = $commitStatus
} | Format-List