import { Injectable } from "@nestjs/common";
import { AiDecisionService } from "../ai-decision/ai-decision.service";
import { PublishJobsService } from "../publish-jobs/publish-jobs.service";
import { AiActionLogService } from "../ai-action-log/ai-action-log.service";

@Injectable()
export class AiPublishingPipelineService {
  constructor(
    private readonly decision: AiDecisionService,
    private readonly publishJobs: PublishJobsService,
    private readonly actionLog: AiActionLogService,
  ) {}

  async run(vehicleId: string) {
    const d = await this.decision.evaluateVehicle(vehicleId);

    const channels = this.selectChannels(d);
    const jobs: any[] = [];

    for (const channel of channels) {
      const creative = this.buildCreative(vehicleId, channel, d);

      const job = await this.publishJobs.createChannelJob(
        vehicleId,
        channel,
        creative.title,
        "queued",
        creative.content,
        {
          decision: d.overallDecision,
          recommendedPrice: d.recommendedPrice,
          estimatedPrice: d.estimatedPrice,
          creative,
        },
      );

      jobs.push(job);

      await this.actionLog.write(
        vehicleId,
        `PUBLISH_JOB_CREATED:${channel}`,
        "completed",
      );
    }

    return {
      success: true,
      vehicleId,
      decision: d.overallDecision,
      selectedChannels: channels,
      jobsCreated: jobs.length,
      jobs,
    };
  }

  private selectChannels(decision: any): string[] {
    const actions = decision.actions ?? [];
    const marketing = decision.summary?.marketing ?? {};
    const exportOpportunity = decision.summary?.exportOpportunity ?? {};
    const buyer = decision.summary?.buyer ?? {};

    const channels = new Set<string>();

    channels.add("website");

    if (actions.includes("START_MARKETING")) {
      for (const c of marketing.channels ?? []) channels.add(c);
    }

    if ((buyer.matchScore ?? 0) >= 85) {
      channels.add("matched_buyers");
      channels.add("crm_leads");
    }

    if ((exportOpportunity.exportScore ?? 0) >= 85) {
      channels.add("gcc_export");
      channels.add("dealer_network");
    }

    return Array.from(channels);
  }

  private buildCreative(vehicleId: string, channel: string, decision: any) {
    const valuation = decision.summary?.valuation ?? {};
    const marketing = decision.summary?.marketing ?? {};
    const trust = decision.summary?.trust ?? {};
    const exportOpportunity = decision.summary?.exportOpportunity ?? {};

    const price = decision.recommendedPrice ?? valuation.recommendedPrice ?? null;

    const title = marketing.headline
      ? `${marketing.headline} - ${channel}`
      : `Smart vehicle listing - ${channel}`;

    const content = [
      `Vehicle ID: ${vehicleId}`,
      price ? `Recommended price: ${price}` : null,
      trust.level ? `Trust level: ${trust.level}` : null,
      exportOpportunity.bestCountry
        ? `Best export market: ${exportOpportunity.bestCountry}`
        : null,
      `Generated by AVOS AI Publishing Pipeline`,
    ]
      .filter(Boolean)
      .join(" | ");

    return {
      title,
      content,
      channel,
      price,
      trustLevel: trust.level ?? null,
      exportMarket: exportOpportunity.bestCountry ?? null,
    };
  }
}
