param(
  [string]$RepoRoot = "C:\Users\User\Desktop\AVOS"
)

$ErrorActionPreference = "Stop"

$GeneratorRoot = Join-Path $RepoRoot "tools\avos-web-pack-generator"
$BlueprintPath = Join-Path $GeneratorRoot "blueprints\web-app-4.json"
$TargetRoot = Join-Path $RepoRoot "apps\web\src\app"

if (-not (Test-Path $BlueprintPath)) {
  throw "Missing blueprint: $BlueprintPath"
}

$Blueprint = Get-Content $BlueprintPath -Raw | ConvertFrom-Json

foreach ($Page in $Blueprint.pages) {
  $PageDir = Join-Path $TargetRoot $Page.route
  New-Item -ItemType Directory -Path $PageDir -Force | Out-Null

  $Title = $Page.title
  $PageName = ($Page.route -replace '[^a-zA-Z0-9]', ' ') -replace '\s+', ''
  if ([string]::IsNullOrWhiteSpace($PageName)) {
    $PageName = "Generated"
  }

  $Content = @"
export default function ${PageName}Page() {
  return (
    <main dir="rtl" className="min-h-screen bg-slate-50 px-6 py-12">
      <div className="mx-auto max-w-7xl">
        <h1 className="text-4xl font-black">$Title</h1>
        <p className="mt-3 text-slate-600">Generated by AVOS Web Pack Generator v1.</p>
      </div>
    </main>
  );
}
"@

  [System.IO.File]::WriteAllText(
    (Join-Path $PageDir "page.tsx"),
    $Content,
    [System.Text.UTF8Encoding]::new($false)
  )
}

Write-Host "AVOS Web App 4.0 generated successfully." -ForegroundColor Green
