export const EXPORT_SHIPPING_CAPABILITIES = [
  "export-only-workflow",
  "shipping-marketplace",
  "carrier-onboarding",
  "carrier-matching",
  "shipping-quotes",
  "customs-foundation",
  "export-documents",
  "document-verification",
  "certificate-of-origin",
  "inspection-certificate",
  "insurance-certificate",
  "bill-of-lading",
  "pickup-scheduling",
  "port-coordination",
  "shipment-tracking",
  "customs-status-tracking",
  "delivery-confirmation",
  "logistics-exceptions",
  "export-analytics",
  "multi-country-export",
] as const;