import { F3Capability } from "./enterprise-ultimate-f3.types";

export const F3_CAPABILITIES: Record<F3Capability, string> = {
  ADVERTISEMENT_COMMAND_CENTER: "Advertisement Command Center",
  SMART_ADVERTISEMENT_CENTER: "Smart Advertisement Center",
  ADVERTISEMENT_INTELLIGENCE: "Advertisement Intelligence",
  ADVERTISEMENT_HEALTH_MONITOR: "Advertisement Health Monitor",
  SALES_PROBABILITY_ENGINE: "Sales Probability Engine",
  AI_PRICE_TIMELINE: "AI Price Timeline",
  AI_PHOTOGRAPHER: "AI Photographer",
  BUYER_RADAR: "Buyer Radar",
  ADVERTISEMENT_BATTLE_MODE: "Advertisement Battle Mode",
  ADVERTISEMENT_LIFECYCLE: "Advertisement Lifecycle",
  MARKETPLACE_INTELLIGENCE: "Marketplace Intelligence",
  MARKET_HEATMAP: "Market Heatmap",
  MARKET_PULSE: "Market Pulse",
  OPPORTUNITY_RADAR: "Opportunity Radar",
  TRUST_SCORE_ENGINE: "Trust Score Engine",
  DEAL_HEALTH_SCORE: "Deal Health Score",
  VEHICLE_360: "Vehicle 360",
  CUSTOMER_360: "Customer 360",
  DEALER_360: "Dealer 360",
  MARKET_360: "Market 360",
  AI_360: "AI 360",
  VEHICLE_TIMELINE: "Vehicle Timeline",
  CUSTOMER_TIMELINE: "Customer Timeline",
  DEAL_TIMELINE: "Deal Timeline",
  SMART_LISTING_RANKING: "Smart Listing Ranking",
  COMPETITOR_COMPARISON: "Competitor Comparison",
  ADVERTISEMENT_AUDIENCE_ANALYTICS: "Advertisement Audience Analytics",
  PROMOTION_OPTIMIZER: "Promotion Optimizer",
  LEAD_INTENT_ENGINE: "Lead Intent Engine",
  MARKETPLACE_COMMAND_CENTER: "Marketplace Command Center",
};