import { AvosCoreFoundation } from "./brand-foundation.types";

export const AVOS_CORE_FOUNDATION: AvosCoreFoundation = {
  version: "1.0.0",
  status: "OFFICIAL",
  mandatoryOrder: [
    "VISION",
    "BRAND_IDENTITY",
    "BRAND_DNA",
    "DESIGN_SYSTEM",
    "CONSTITUTIONAL_FOUNDATION",
    "STRATEGIC_FOUNDATION",
    "PLATFORM_FOUNDATION",
    "PRODUCT_ARCHITECTURE",
    "PRODUCT_DEVELOPMENT",
  ],
  brandIdentity: {
    brandName: "AVOS Enterprise",
    officialTagline: "The Operating System for Mobility",
    officialLogo: "AV Wing Motion",
    personality: [
      "PREMIUM",
      "AI_FIRST",
      "GLOBAL",
      "TRUSTED",
      "INTELLIGENT",
      "SCALABLE",
    ],
  },
  brandDna: {
    principles: [
      "Simplicity",
      "Intelligence",
      "Enterprise Quality",
      "Reliability",
      "Trust",
      "Innovation",
      "Global Readiness",
    ],
    experienceAttributes: [
      "Clear",
      "Premium",
      "Confident",
      "Accessible",
      "Human-Centered",
      "AI-Assisted",
    ],
    productBehavior: [
      "Consistent across all products",
      "Secure by default",
      "Accessible by default",
      "Scalable by design",
      "Observable in production",
      "Governed by platform standards",
    ],
  },
  designSystem: {
    required: true,
    tokens: [
      "Color Tokens",
      "Typography Tokens",
      "Spacing Tokens",
      "Radius Tokens",
      "Shadow Tokens",
      "Motion Tokens",
      "Elevation Tokens",
      "Semantic Tokens",
    ],
    standards: [
      "Responsive Layout",
      "Accessible Components",
      "Reusable Components",
      "Consistent Navigation",
      "Bilingual Readiness",
      "Light Theme First",
      "AI Experience Standards",
      "Enterprise Dashboard Standards",
    ],
    accessibilityRequired: true,
    responsiveRequired: true,
  },
  appliesTo: [
    "Applications",
    "Websites",
    "Dashboards",
    "Mobile Apps",
    "AI Systems",
    "APIs",
    "Industry Packs",
    "Marketplace Experiences",
    "Marketing Materials",
    "Documentation",
    "Partner Portals",
    "Administrative Consoles",
  ],
  governanceRules: [
    "No AVOS product may begin directly from product development",
    "Every product must inherit the official brand identity",
    "Every product must use the official design system",
    "Every new industry pack must register against the core foundation",
    "Every interface must support accessibility and responsive behavior",
    "Every product must pass architecture and production readiness gates",
  ],
  qualityGates: [
    "TypeScript",
    "Build",
    "Flutter Analyze",
    "Smoke Tests",
    "Integration Tests",
    "Verification",
    "Git Working Tree Clean",
  ],
};