import { Injectable } from '@nestjs/common';
import { UltimateProductRequest } from './product-factory-ultimate.types';

@Injectable()
export class UltimateTemplateService {
  packageJson(request: UltimateProductRequest): string {
    return JSON.stringify({
      name: `@avos-generated/${request.namespace}`,
      version: request.version || '1.0.0',
      private: true,
      scripts: {
        typecheck: 'tsc --noEmit',
        build: 'tsc -p tsconfig.json',
        test: 'node dist/tests/smoke.js',
        start: 'node dist/backend/server.js',
      },
      devDependencies: {
        '@types/node': '^22.0.0',
        typescript: '^6.0.0',
      },
    }, null, 2) + '\n';
  }

  tsconfig(): string {
    return JSON.stringify({
      compilerOptions: {
        target: 'ES2022',
        module: 'Node16',
        moduleResolution: 'Node16',
        types: ['node'],
        outDir: 'dist',
        rootDir: '.',
        strict: true,
        esModuleInterop: true,
        skipLibCheck: true,
        forceConsistentCasingInFileNames: true,
      },
      include: ['backend/**/*.ts', 'shared/**/*.ts', 'tests/**/*.ts'],
    }, null, 2) + '\n';
  }

  backend(request: UltimateProductRequest): string {
    const safeName = JSON.stringify(request.productName);
    return `import { createServer } from 'node:http';

export const product = {
  name: ${safeName},
  namespace: ${JSON.stringify(request.namespace)},
  version: ${JSON.stringify(request.version || '1.0.0')},
  status: 'operational' as const,
  humanFinalAuthority: true,
  globalComplianceReadinessGate: true,
};

if (require.main === module) {
  const server = createServer((_request, response) => {
    response.writeHead(200, { 'content-type': 'application/json' });
    response.end(JSON.stringify(product));
  });
  server.listen(0);
}
`;
  }

  sharedTypes(request: UltimateProductRequest): string {
    const entities = request.entities?.length ? request.entities : ['ProductRecord'];
    return `export type GeneratedEntityName = ${entities.map((x) => JSON.stringify(x)).join(' | ')};

export interface GeneratedProductMetadata {
  productName: string;
  namespace: string;
  version: string;
  approvedBy: string;
}
`;
  }

  smoke(): string {
    return `import { strict as assert } from 'node:assert';
import { product } from '../backend/server';

assert.equal(product.status, 'operational');
assert.equal(product.humanFinalAuthority, true);
assert.equal(product.globalComplianceReadinessGate, true);
console.log(JSON.stringify({ status: 'passed', score: 100, product }));
`;
  }

  prisma(request: UltimateProductRequest): string {
    const models = (request.entities?.length ? request.entities : ['ProductRecord']).map((entity) => {
      const model = entity.replace(/[^A-Za-z0-9_]/g, '') || 'ProductRecord';
      return `model ${model} {
  id        String   @id @default(cuid())
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
}`;
    }).join('\n\n');
    return `generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

${models}
`;
  }

  web(request: UltimateProductRequest): string {
    return `<!doctype html>
<html lang="en">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>${request.productName}</title></head>
<body>
  <main>
    <h1>${request.productName}</h1>
    <p>${request.description || 'Generated by AVOS Product Factory Ultimate.'}</p>
    <p>Foundation First · Capability First · Human Final Authority</p>
  </main>
</body>
</html>
`;
  }

  dockerfile(): string {
    return `FROM node:22-alpine
WORKDIR /app
COPY package.json tsconfig.json ./
COPY backend ./backend
COPY shared ./shared
COPY tests ./tests
RUN corepack enable && pnpm install --frozen-lockfile=false && pnpm build
CMD ["node", "dist/backend/server.js"]
`;
  }

  workflow(): string {
    return `name: Generated Product CI
on:
  push:
  pull_request:
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
      - run: pnpm install --frozen-lockfile=false
      - run: pnpm typecheck
      - run: pnpm build
      - run: pnpm test
`;
  }
}
