"use client";

const capabilities = [
  "Customer 360",
  "Customer Journey Genome",
  "Retention Intelligence",
  "Loyalty Optimization",
  "Personalization Engine",
  "Customer Risk Radar",
  "Lifetime Value Forecast",
  "Next Best Action",
  "Experience Orchestration",
  "Voice Of Customer",
  "Customer Recovery",
  "Customer Evidence",
];

export default function EnterpriseCustomerIntelligenceG4Page() {
  return (
    <main style={{ maxWidth: 1180, margin: "0 auto", padding: "48px 24px" }}>
      <p style={{ letterSpacing: 2, textTransform: "uppercase", opacity: 0.65 }}>
        AVOS Enterprise Production
      </p>
      <h1 style={{ fontSize: 48, margin: "12px 0" }}>AVOS Enterprise Customer Intelligence Mega Bundle G4</h1>
      <p style={{ fontSize: 18, lineHeight: 1.7, opacity: 0.78 }}>
        Generated by AVOS Pack Builder V2.
      </p>
      <section style={{
        display: "grid",
        gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))",
        gap: 16,
        marginTop: 32
      }}>
        {capabilities.map((capability) => (
          <article key={capability} style={{
            border: "1px solid rgba(0,0,0,.12)",
            borderRadius: 18,
            padding: 20
          }}>
            <strong>{capability}</strong>
          </article>
        ))}
      </section>
    </main>
  );
}