export const INDUSTRY_PACK_CATALOG = {
  AUTOMOTIVE: {
    code: "AUTOMOTIVE",
    name: "Automotive Industry Pack",
    sourceModule: "AutomotiveIndustryModule",
    sourcePath: "automotive-industry",
    industryCount: 1,
    version: "1.0.0",
  },
  HEAVY_EQUIPMENT: {
    code: "HEAVY_EQUIPMENT",
    name: "Heavy Equipment Industry Pack",
    sourceModule: "HeavyEquipmentIndustryModule",
    sourcePath: "heavy-equipment-industry",
    industryCount: 1,
    version: "1.0.0",
  },
  INDUSTRY_MEGA_BUNDLE_1: {
    code: "INDUSTRY_MEGA_BUNDLE_1",
    name: "Industry Mega Bundle 1",
    sourceModule: "IndustryMegaBundle1Module",
    sourcePath: "industry-mega-bundle-1",
    industryCount: 5,
    version: "1.0.0",
  },
  INDUSTRY_ULTRA_BUNDLE_2_3: {
    code: "INDUSTRY_ULTRA_BUNDLE_2_3",
    name: "Industry Ultra Bundle 2-3",
    sourceModule: "IndustryUltraBundle23Module",
    sourcePath: "industry-ultra-bundle-2-3",
    industryCount: 10,
    version: "1.0.0",
  },
  INDUSTRY_ULTRA_BUNDLE_4_5: {
    code: "INDUSTRY_ULTRA_BUNDLE_4_5",
    name: "Industry Ultra Bundle 4-5",
    sourceModule: "IndustryUltraBundle45Module",
    sourcePath: "industry-ultra-bundle-4-5",
    industryCount: 10,
    version: "1.0.0",
  },
} as const;

export const UNIVERSAL_CAPABILITY_MAPPING: Record<string, string> = {
  OPERATIONS: "INDUSTRY_ENGINE",
  CORE_OPERATIONS: "INDUSTRY_ENGINE",
  ASSET_MANAGEMENT: "ASSET_ENGINE",
  ASSET_RESOURCE_MANAGEMENT: "ASSET_ENGINE",
  FINANCE: "FINANCE_ENGINE",
  FINANCE_REVENUE: "FINANCE_ENGINE",
  FINANCE_FUNDING: "FINANCE_ENGINE",
  COMPLIANCE: "COMPLIANCE_ENGINE",
  COMPLIANCE_SAFETY: "COMPLIANCE_ENGINE",
  RISK: "RISK_ENGINE",
  RISK_RESILIENCE: "RISK_ENGINE",
  AI_INTELLIGENCE: "AI_INTELLIGENCE",
  ANALYTICS: "ANALYTICS_ENGINE",
  ANALYTICS_IMPACT: "ANALYTICS_ENGINE",
  AUTOMATION: "AUTOMATION_ENGINE",
  DOCUMENTS: "DOCUMENT_ENGINE",
  DOCUMENTS_CASES: "DOCUMENT_ENGINE",
  NOTIFICATIONS: "NOTIFICATION_ENGINE",
  NOTIFICATIONS_RESPONSE: "NOTIFICATION_ENGINE",
  COMMAND_CENTER: "COMMAND_CENTER",
  MARKETPLACE: "INTEGRATION_ENGINE",
  MARKETPLACE_ECOSYSTEM: "INTEGRATION_ENGINE",
  ECOSYSTEM_MARKETPLACE: "INTEGRATION_ENGINE",
};