export const INDUSTRY_GOVERNANCE_PARTNER_COMPONENTS = [
  "governance-foundation",
  "permissions-foundation",
  "role-policy-engine",
  "approval-workflow-engine",
  "compliance-foundation",
  "regulatory-check-engine",
  "risk-assessment-engine",
  "fraud-control-foundation",
  "partner-onboarding",
  "partner-verification",
  "partner-agreements",
  "partner-sla-management",
  "partner-performance",
  "partner-settlements",
  "partner-disputes",
  "audit-trail-foundation",
  "constitutional-policy-foundation",
  "executive-approval-center",
  "partner-command-center",
] as const;

export const SUPPORTED_GOVERNANCE_INDUSTRIES = [
  "cars",
  "motorcycles",
  "buggy",
  "heavy-equipment",
  "marine",
  "aviation",
  "camping",
  "trucks",
  "buses",
  "caravans",
] as const;