import "package:flutter/material.dart";

class {{MOBILE_CLASS}} extends StatelessWidget {
  const {{MOBILE_CLASS}}({super.key});

  static const capabilities = <String>[
{{FLUTTER_CAPABILITIES}}
  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text("{{TITLE}}")),
      body: ListView.separated(
        padding: const EdgeInsets.all(16),
        itemCount: capabilities.length,
        separatorBuilder: (_, __) => const SizedBox(height: 10),
        itemBuilder: (context, index) => Card(
          child: ListTile(
            leading: const Icon(Icons.auto_awesome),
            title: Text(capabilities[index]),
            subtitle: const Text("Generated by AVOS Pack Builder V2"),
          ),
        ),
      ),
    );
  }
}