# {{TITLE}}

Generated by **AVOS Pack Builder V2**.

- Code: `{{CODE}}`
- Module: `{{MODULE_SLUG}}`
- Blueprint schema: `2.0`
- Capabilities: {{CAPABILITY_COUNT}}
- Entities: {{ENTITY_COUNT}}
- API route: `/{{MODULE_SLUG}}/status`
- Web route: `/{{MODULE_SLUG}}`

## Generated targets

- NestJS module, controller, service, registry, types, entities and DTOs
- Next.js page
- Flutter feature screen
- Smoke, integration and verification scripts
- Evidence manifest and rollback-safe backup