import {
  CapabilityDefinition,
  DependencyEdge,
  FoundationContract,
  FoundationPolicy,
  FoundationSchema,
} from "./foundation-framework.types";

export const FOUNDATION_CAPABILITIES: CapabilityDefinition[] = [
  {
    id: "capability-registry",
    name: "Capability Registry",
    description: "Single source of truth for every AVOS capability.",
    domain: "foundation",
    owner: "AVOS Architecture",
    version: "1.0.0",
    lifecycle: "PRODUCTION",
    dependencies: [],
    securityLevel: "INTERNAL",
    aiLevel: "ASSISTED",
    events: ["FoundationCapabilityRegistered"],
    apis: ["/foundation-framework/capabilities"],
    tags: ["registry", "architecture", "governance"],
  },
  {
    id: "enterprise-dependency-graph",
    name: "Enterprise Dependency Graph",
    description: "Tracks dependencies and enables impact analysis.",
    domain: "foundation",
    owner: "AVOS Architecture",
    version: "1.0.0",
    lifecycle: "PRODUCTION",
    dependencies: ["capability-registry"],
    securityLevel: "INTERNAL",
    aiLevel: "ASSISTED",
    events: ["FoundationDependencyRegistered"],
    apis: ["/foundation-framework/dependencies"],
    tags: ["dependency", "impact-analysis"],
  },
  {
    id: "standards-engine",
    name: "Standards Engine",
    description: "Defines mandatory engineering and product standards.",
    domain: "foundation",
    owner: "AVOS Governance",
    version: "1.0.0",
    lifecycle: "PRODUCTION",
    dependencies: ["capability-registry"],
    securityLevel: "INTERNAL",
    aiLevel: "ASSISTED",
    events: ["FoundationStandardEvaluated"],
    apis: [],
    tags: ["standards", "quality"],
  },
  {
    id: "architecture-validator",
    name: "Architecture Validator",
    description: "Detects foundation and architecture violations.",
    domain: "foundation",
    owner: "AVOS Architecture",
    version: "1.0.0",
    lifecycle: "PRODUCTION",
    dependencies: ["standards-engine", "enterprise-dependency-graph"],
    securityLevel: "INTERNAL",
    aiLevel: "ASSISTED",
    events: ["FoundationArchitectureValidated"],
    apis: ["/foundation-framework/validate"],
    tags: ["validation", "architecture"],
  },
  {
    id: "enterprise-contract-registry",
    name: "Enterprise Contract Registry",
    description: "Registers versioned API, event, AI and integration contracts.",
    domain: "foundation",
    owner: "AVOS Platform",
    version: "1.0.0",
    lifecycle: "PRODUCTION",
    dependencies: ["capability-registry"],
    securityLevel: "CONFIDENTIAL",
    aiLevel: "NONE",
    events: ["FoundationContractRegistered"],
    apis: ["/foundation-framework/contracts"],
    tags: ["contracts", "compatibility"],
  },
  {
    id: "platform-metadata-engine",
    name: "Platform Metadata Engine",
    description: "Defines shared metadata for AVOS platform objects.",
    domain: "foundation",
    owner: "AVOS Data",
    version: "1.0.0",
    lifecycle: "PRODUCTION",
    dependencies: ["capability-registry"],
    securityLevel: "CONFIDENTIAL",
    aiLevel: "ASSISTED",
    events: ["FoundationMetadataAssigned"],
    apis: [],
    tags: ["metadata", "data-governance"],
  },
  {
    id: "domain-definition-framework",
    name: "Domain Definition Framework",
    description: "Defines official domains and bounded contexts.",
    domain: "foundation",
    owner: "AVOS Architecture",
    version: "1.0.0",
    lifecycle: "PRODUCTION",
    dependencies: ["capability-registry"],
    securityLevel: "INTERNAL",
    aiLevel: "NONE",
    events: ["FoundationDomainDefined"],
    apis: [],
    tags: ["domain", "bounded-context"],
  },
  {
    id: "enterprise-policy-registry",
    name: "Enterprise Policy Registry",
    description: "Central registry for executable enterprise policies.",
    domain: "foundation",
    owner: "AVOS Governance",
    version: "1.0.0",
    lifecycle: "PRODUCTION",
    dependencies: ["capability-registry"],
    securityLevel: "RESTRICTED",
    aiLevel: "ASSISTED",
    events: ["FoundationPolicyRegistered"],
    apis: ["/foundation-framework/policies"],
    tags: ["policy", "governance"],
  },
  {
    id: "enterprise-schema-registry",
    name: "Enterprise Schema Registry",
    description: "Registers versioned schemas and compatibility modes.",
    domain: "foundation",
    owner: "AVOS Data",
    version: "1.0.0",
    lifecycle: "PRODUCTION",
    dependencies: ["enterprise-contract-registry"],
    securityLevel: "CONFIDENTIAL",
    aiLevel: "NONE",
    events: ["FoundationSchemaRegistered"],
    apis: ["/foundation-framework/schemas"],
    tags: ["schema", "versioning"],
  },
  {
    id: "foundation-compliance-engine",
    name: "Foundation Compliance Engine",
    description: "Blocks bundles that violate mandatory foundation rules.",
    domain: "foundation",
    owner: "AVOS Governance",
    version: "1.0.0",
    lifecycle: "PRODUCTION",
    dependencies: [
      "architecture-validator",
      "enterprise-contract-registry",
      "enterprise-policy-registry",
      "enterprise-schema-registry",
    ],
    securityLevel: "RESTRICTED",
    aiLevel: "ASSISTED",
    events: ["FoundationComplianceEvaluated"],
    apis: ["/foundation-framework/status", "/foundation-framework/validate"],
    tags: ["compliance", "quality-gate"],
  },
  {
    id: "enterprise-knowledge-registry",
    name: "Enterprise Knowledge Registry",
    description: "Maps official AVOS definitions and architectural decisions.",
    domain: "foundation",
    owner: "AVOS Knowledge",
    version: "1.0.0",
    lifecycle: "PRODUCTION",
    dependencies: ["capability-registry"],
    securityLevel: "INTERNAL",
    aiLevel: "ASSISTED",
    events: ["FoundationKnowledgeRegistered"],
    apis: [],
    tags: ["knowledge", "adr"],
  },
  {
    id: "enterprise-blueprint-registry",
    name: "Enterprise Blueprint Registry",
    description: "Registers blueprints, templates and CodeGen assets.",
    domain: "foundation",
    owner: "AVOS Genesis",
    version: "1.0.0",
    lifecycle: "PRODUCTION",
    dependencies: ["capability-registry", "enterprise-contract-registry"],
    securityLevel: "CONFIDENTIAL",
    aiLevel: "ASSISTED",
    events: ["FoundationBlueprintRegistered"],
    apis: [],
    tags: ["blueprint", "codegen", "genesis"],
  },
  {
    id: "platform-health-rules",
    name: "Platform Health Rules",
    description: "Defines platform quality and production-readiness baselines.",
    domain: "foundation",
    owner: "AVOS Reliability",
    version: "1.0.0",
    lifecycle: "PRODUCTION",
    dependencies: ["foundation-compliance-engine"],
    securityLevel: "INTERNAL",
    aiLevel: "ASSISTED",
    events: ["FoundationHealthMeasured"],
    apis: ["/foundation-framework/status"],
    tags: ["health", "readiness"],
  },
  {
    id: "enterprise-lifecycle-manager",
    name: "Enterprise Lifecycle Manager",
    description: "Controls lifecycle states for AVOS components.",
    domain: "foundation",
    owner: "AVOS Governance",
    version: "1.0.0",
    lifecycle: "PRODUCTION",
    dependencies: ["capability-registry"],
    securityLevel: "CONFIDENTIAL",
    aiLevel: "ASSISTED",
    events: ["FoundationLifecycleChanged"],
    apis: [],
    tags: ["lifecycle", "governance"],
  },
  {
    id: "foundation-governance-layer",
    name: "Foundation Governance Layer",
    description: "Highest governance layer for architecture and releases.",
    domain: "foundation",
    owner: "AVOS Governance Council",
    version: "1.0.0",
    lifecycle: "PRODUCTION",
    dependencies: ["foundation-compliance-engine", "enterprise-lifecycle-manager"],
    securityLevel: "RESTRICTED",
    aiLevel: "AUTONOMOUS",
    events: ["FoundationGovernanceDecisionIssued"],
    apis: [],
    tags: ["governance", "constitution"],
  },
];

export const FOUNDATION_DEPENDENCIES: DependencyEdge[] =
  FOUNDATION_CAPABILITIES.flatMap((capability) =>
    capability.dependencies.map((dependency) => ({
      source: capability.id,
      target: dependency,
      type: "REQUIRES" as const,
      required: true,
    })),
  );

export const FOUNDATION_CONTRACTS: FoundationContract[] = [
  {
    id: "foundation-status-v1",
    name: "Foundation Status API",
    type: "API",
    version: "1.0.0",
    owner: "AVOS Foundation",
    backwardCompatible: true,
  },
  {
    id: "foundation-validation-v1",
    name: "Foundation Validation API",
    type: "API",
    version: "1.0.0",
    owner: "AVOS Foundation",
    backwardCompatible: true,
  },
  {
    id: "foundation-events-v1",
    name: "Foundation Domain Events",
    type: "EVENT",
    version: "1.0.0",
    owner: "AVOS Foundation",
    backwardCompatible: true,
  },
];

export const FOUNDATION_POLICIES: FoundationPolicy[] = [
  {
    id: "architecture-compliance",
    name: "Architecture Compliance",
    domain: "foundation",
    version: "1.0.0",
    enabled: true,
    enforcement: "BLOCKING",
  },
  {
    id: "contract-versioning",
    name: "Contract Versioning",
    domain: "foundation",
    version: "1.0.0",
    enabled: true,
    enforcement: "MANDATORY",
  },
  {
    id: "security-by-default",
    name: "Security by Default",
    domain: "security",
    version: "1.0.0",
    enabled: true,
    enforcement: "BLOCKING",
  },
  {
    id: "audit-by-default",
    name: "Audit by Default",
    domain: "compliance",
    version: "1.0.0",
    enabled: true,
    enforcement: "MANDATORY",
  },
];

export const FOUNDATION_SCHEMAS: FoundationSchema[] = [
  {
    id: "capability-definition-v1",
    name: "Capability Definition",
    type: "DTO",
    version: "1.0.0",
    compatibility: "BACKWARD",
  },
  {
    id: "foundation-compliance-report-v1",
    name: "Foundation Compliance Report",
    type: "API",
    version: "1.0.0",
    compatibility: "BACKWARD",
  },
  {
    id: "foundation-event-envelope-v1",
    name: "Foundation Event Envelope",
    type: "EVENT",
    version: "1.0.0",
    compatibility: "FULL",
  },
];
