import { F1Capability } from "./enterprise-ultimate-f1.types";

export const F1_CAPABILITIES: Record<F1Capability, string> = {
  WORKFLOW_ENGINE_V2: "Enterprise Workflow Engine V2",
  UNIVERSAL_NOTIFICATION_CENTER: "Universal Notification Center",
  ENTERPRISE_COMMAND_BUS: "Enterprise Command Bus",
  GLOBAL_SEARCH_ENGINE: "Global Search Engine",
  ENTERPRISE_DASHBOARD_ENGINE: "Enterprise Dashboard Engine",
  WIDGET_FRAMEWORK: "Widget Framework",
  DYNAMIC_DASHBOARD_BUILDER: "Dynamic Dashboard Builder",
  AI_WORKSPACE_ENGINE: "AI Workspace Engine",
  ENTERPRISE_TIMELINE_ENGINE: "Enterprise Timeline Engine",
  LIVE_ACTIVITY_ENGINE: "Live Activity Engine",
  REAL_TIME_EVENT_STREAM: "Real-time Event Stream",
  ENTERPRISE_KPI_ENGINE: "Enterprise KPI Engine",
  CROSS_MODULE_ANALYTICS: "Cross-Module Analytics",
  DASHBOARD_PERMISSION_ENGINE: "Dashboard Permission Engine",
  ENTERPRISE_COMMAND_CENTER_CORE: "Enterprise Command Center Core",
  BUSINESS_PULSE_ENGINE: "Business Pulse Engine",
  AI_RECOMMENDATION_ENGINE_V2: "AI Recommendation Engine V2",
  UNIFIED_NAVIGATION_FRAMEWORK: "Unified Navigation Framework",
  WORKSPACE_PERSONALIZATION: "Workspace Personalization",
  ENTERPRISE_THEME_SYSTEM: "Enterprise Theme System",
  MULTI_TENANT_DASHBOARD_PROFILES: "Multi-Tenant Dashboard Profiles",
  DASHBOARD_LAYOUT_MANAGER: "Dashboard Layout Manager",
  ENTERPRISE_LIVE_WIDGETS: "Enterprise Live Widgets",
  ENTERPRISE_ACTIVITY_FEED: "Enterprise Activity Feed",
  DASHBOARD_PERFORMANCE_OPTIMIZER: "Dashboard Performance Optimizer",
};