"use client";

const capabilities = [
  "Master Data Hub",
  "Universal Customer 360",
  "Universal Asset Registry",
  "Enterprise Data Fabric",
  "Enterprise Search Fabric",
  "Data Lineage",
  "Data Quality",
  "Schema Federation",
  "Real Time Data Mesh",
  "Data Governance",
];

export default function UniversalDataFabricPage() {
  return (
    <main style={{ maxWidth: 1180, margin: "0 auto", padding: "48px 24px" }}>
      <p style={{ letterSpacing: 2, textTransform: "uppercase", opacity: 0.65 }}>
        AVOS Enterprise Production
      </p>
      <h1 style={{ fontSize: 48, margin: "12px 0" }}>AVOS Universal Data Fabric</h1>
      <p style={{ fontSize: 18, lineHeight: 1.7, opacity: 0.78 }}>
        Generated by AVOS Pack Builder V2.
      </p>
      <section style={{
        display: "grid",
        gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))",
        gap: 16,
        marginTop: 32
      }}>
        {capabilities.map((capability) => (
          <article key={capability} style={{
            border: "1px solid rgba(0,0,0,.12)",
            borderRadius: 18,
            padding: 20
          }}>
            <strong>{capability}</strong>
          </article>
        ))}
      </section>
    </main>
  );
}