export const FOUNDATION_COMPONENTS = [
  "core-platform-foundation",
  "industry-based-architecture",
  "commerce-engine-foundation",
  "revenue-engine-foundation",
  "revenue-protection-foundation",
  "audit-tracking-engine",
  "governance-permissions-foundation",
  "event-tracking-foundation",
  "lead-deal-pipeline-foundation",
  "shared-business-capabilities-foundation",
  "command-center-foundation",
  "owner-ai-foundation",
  "executive-dashboard-foundation",
  "business-intelligence-foundation",
  "constitution-governance-foundation",
  "executive-management-foundation",
  "platform-registry-foundation",
  "industry-registry-foundation",
  "capability-registry-foundation",
] as const;

export const DEFAULT_SHARED_CAPABILITIES = [
  "commerce",
  "revenue",
  "payments",
  "subscriptions",
  "audit",
  "governance",
  "events",
  "lead-deal",
  "analytics",
  "command-center",
  "owner-ai",
] as const;