export const GENESIS_CAPABILITIES = {
  DEPLOYMENT_GENERATOR: "Deployment Generator",
  INFRASTRUCTURE_GENERATOR: "Infrastructure Generator",
  VALIDATION_ENGINE: "Validation Engine",
  QUALITY_GATE: "Quality Gate",
  RELEASE_MANAGER: "Release Manager",
  ROLLBACK_MANAGER: "Rollback Manager",
  VERSION_MANAGER: "Version Manager",
  KNOWLEDGE_REGISTRATION: "Knowledge Registration",
  ENTERPRISE_BRAIN_INTEGRATION: "Enterprise Brain Integration",
  EVOLUTION_CENTER_INTEGRATION: "Evolution Center Integration",
  MARKETPLACE_PUBLISHER: "Marketplace Publisher",
  GLOBAL_COMMAND_CENTER: "Global Command Center",
} as const;

export const GENESIS_CAPABILITY_CODES = [
  "DEPLOYMENT_GENERATOR",
  "INFRASTRUCTURE_GENERATOR",
  "VALIDATION_ENGINE",
  "QUALITY_GATE",
  "RELEASE_MANAGER",
  "ROLLBACK_MANAGER",
  "VERSION_MANAGER",
  "KNOWLEDGE_REGISTRATION",
  "ENTERPRISE_BRAIN_INTEGRATION",
  "EVOLUTION_CENTER_INTEGRATION",
  "MARKETPLACE_PUBLISHER",
  "GLOBAL_COMMAND_CENTER",
] as const;