import { Injectable, OnModuleInit } from "@nestjs/common";
import { TemplateRegistry } from "../registry/template.registry";

@Injectable()
export class DefaultTemplatesService implements OnModuleInit {
  constructor(private readonly registry: TemplateRegistry) {}

  onModuleInit(): void {
    this.registry.register("module", `import { Module } from "@nestjs/common";

@Module({
  providers: [],
  controllers: [],
  exports: [],
})
export class {{className}}Module {}
`);
    this.registry.register("service", `import { Injectable } from "@nestjs/common";

@Injectable()
export class {{className}}Service {
  status() {
    return { service: "{{className}}", healthy: true };
  }
}
`);
    this.registry.register("controller", `import { Controller, Get } from "@nestjs/common";

@Controller("{{route}}")
export class {{className}}Controller {
  @Get("status")
  status() {
    return { controller: "{{className}}", healthy: true };
  }
}
`);
    this.registry.register("dto", `import { IsNotEmpty, IsString } from "class-validator";

export class {{className}}Dto {
  @IsString()
  @IsNotEmpty()
  name!: string;
}
`);
    this.registry.register("interface", `export interface {{className}} {
  id: string;
  createdAt: string;
}
`);
    this.registry.register("test", `describe("{{className}}", () => {
  it("should be defined", () => {
    expect(true).toBe(true);
  });
});
`);
    this.registry.register("documentation", `# {{className}}

Generated by AVOS Code Generation OS.
`);
  }
}
