import { BadRequestException, Injectable } from '@nestjs/common';
import { join } from 'node:path';
import { ProductGenerationStore } from './product-generation.store';
import { FilesystemWriterService } from './filesystem-writer.service';

@Injectable()
export class FrontendGeneratorService {
  constructor(
    private readonly store: ProductGenerationStore,
    private readonly writer: FilesystemWriterService,
  ) {}

  async generate(namespace: string, outputRoot: string): Promise<string[]> {
    const specification = this.store.specifications.get(namespace);
    const architecture = this.store.architectures.get(namespace);
    if (!specification || !architecture) {
      throw new BadRequestException(`Specification or architecture missing: ${namespace}`);
    }

    const root = join(outputRoot, namespace, 'frontend');
    const files: string[] = [];

    files.push(
      await this.writer.write(
        root,
        'package.json',
        JSON.stringify(
          {
            name: `${namespace}-web`,
            private: true,
            scripts: {
              dev: 'next dev',
              build: 'next build',
              start: 'next start',
            },
            dependencies: {
              next: '^15.5.0',
              react: '^19.0.0',
              'react-dom': '^19.0.0',
            },
            devDependencies: {
              '@types/node': '^22.0.0',
              '@types/react': '^19.0.0',
              typescript: '^5.7.0',
            },
          },
          null,
          2,
        ),
      ),
    );

    files.push(
      await this.writer.write(
        root,
        'tsconfig.json',
        JSON.stringify(
          {
            compilerOptions: {
              target: 'ES2017',
              lib: ['dom', 'dom.iterable', 'esnext'],
              allowJs: false,
              skipLibCheck: true,
              strict: true,
              noEmit: true,
              esModuleInterop: true,
              module: 'esnext',
              moduleResolution: 'bundler',
              resolveJsonModule: true,
              isolatedModules: true,
              jsx: 'preserve',
              incremental: true,
              plugins: [{ name: 'next' }],
            },
            include: ['next-env.d.ts', '**/*.ts', '**/*.tsx', '.next/types/**/*.ts'],
            exclude: ['node_modules'],
          },
          null,
          2,
        ),
      ),
    );

    files.push(
      await this.writer.write(
        root,
        'app/layout.tsx',
        `export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body style={{ margin: 0, fontFamily: 'Arial, sans-serif', background: '#071426', color: '#f4d77b' }}>
        {children}
      </body>
    </html>
  );
}
`,
      ),
    );

    files.push(
      await this.writer.write(
        root,
        'app/page.tsx',
        `const pages = ${JSON.stringify(architecture.pages)};

export default function HomePage() {
  return (
    <main style={{ padding: 48 }}>
      <h1>${specification.name}</h1>
      <p>${specification.description}</p>
      <p>Generated by AVOS Product Factory.</p>
      <section style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(220px,1fr))', gap: 16 }}>
        {pages.map((page) => (
          <article key={page} style={{ border: '1px solid #f4d77b', borderRadius: 12, padding: 20 }}>
            <h2>{page}</h2>
            <p>Generated operational workspace.</p>
          </article>
        ))}
      </section>
    </main>
  );
}
`,
      ),
    );

    files.push(
      await this.writer.write(
        root,
        'lib/api.ts',
        `const API_URL = process.env.NEXT_PUBLIC_API_URL ?? 'http://localhost:3100/api';

export async function apiGet<T>(resource: string): Promise<T> {
  const response = await fetch(\`\${API_URL}/\${resource}\`, { cache: 'no-store' });
  if (!response.ok) throw new Error(\`API request failed: \${response.status}\`);
  return response.json() as Promise<T>;
}
`,
      ),
    );

    for (const page of architecture.pages) {
      files.push(
        await this.writer.write(
          root,
          `app/${page}/page.tsx`,
          `export default function GeneratedPage() {
  return (
    <main style={{ padding: 48 }}>
      <h1>${page}</h1>
      <p>Generated page for ${specification.name}.</p>
    </main>
  );
}
`,
        ),
      );
    }

    return files;
  }
}