export const RUNTIME_EXECUTION_FOUNDATION_VERSION = "1.0.0";
export const DEFAULT_EXECUTION_RETRIES = 3;
export const DEFAULT_RUNTIME_HEALTH_THRESHOLD = 80;
export const DEFAULT_RECOVERY_TIMEOUT_MS = 30000;
