apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: avos-default-deny
  namespace: avos-enterprise
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: avos-web-to-api
  namespace: avos-enterprise
spec:
  podSelector:
    matchLabels:
      app: avos-api
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: avos-web
      ports:
        - protocol: TCP
          port: 3000