import type { RuntimeApplication } from "./types";

export const runtimeApplications: RuntimeApplication[] = [
  {
    id: "command-center",
    name: "Enterprise Command Center",
    route: "/control-center",
    category: "Executive",
    version: "2.0.0",
    health: "healthy",
    enabled: true,
    permissions: ["executive.read"],
    tenantAware: true,
    pluginCount: 4,
  },
  {
    id: "marketplace",
    name: "Marketplace AI",
    route: "/marketplace",
    category: "Marketplace",
    version: "2.0.0",
    health: "healthy",
    enabled: true,
    permissions: ["marketplace.read"],
    tenantAware: true,
    pluginCount: 3,
  },
  {
    id: "admin",
    name: "Admin Console",
    route: "/admin",
    category: "Workspace",
    version: "2.0.0",
    health: "healthy",
    enabled: true,
    permissions: ["admin.read"],
    tenantAware: true,
    pluginCount: 6,
  },
  {
    id: "portal",
    name: "User Portal",
    route: "/portal",
    category: "Workspace",
    version: "2.0.0",
    health: "healthy",
    enabled: true,
    permissions: ["portal.read"],
    tenantAware: true,
    pluginCount: 2,
  },
];
