import { FoundationCapability } from "./enterprise-foundations.types";

export const ENTERPRISE_FOUNDATION_CAPABILITIES: FoundationCapability[] = [
  { key: "data-governance", name: "Data Governance", domain: "DATA_AI", reusable: true, multiIndustry: true, active: true },
  { key: "metadata-catalog", name: "Metadata Catalog", domain: "DATA_AI", reusable: true, multiIndustry: true, active: true },
  { key: "master-data-management", name: "Master Data Management", domain: "DATA_AI", reusable: true, multiIndustry: true, active: true },
  { key: "data-lineage", name: "Data Lineage", domain: "DATA_AI", reusable: true, multiIndustry: true, active: true },
  { key: "data-quality", name: "Data Quality Engine", domain: "DATA_AI", reusable: true, multiIndustry: true, active: true },
  { key: "feature-store", name: "Feature Store", domain: "DATA_AI", reusable: true, multiIndustry: true, active: true },
  { key: "ai-model-registry", name: "AI Model Registry", domain: "DATA_AI", reusable: true, multiIndustry: true, active: true },
  { key: "ai-training-pipeline", name: "AI Training Pipeline", domain: "DATA_AI", reusable: true, multiIndustry: true, active: true },
  { key: "model-monitoring", name: "Model Monitoring", domain: "DATA_AI", reusable: true, multiIndustry: true, active: true },
  { key: "responsible-ai", name: "Responsible AI Governance", domain: "DATA_AI", reusable: true, multiIndustry: true, active: true },
  { key: "knowledge-graph", name: "Knowledge Graph Foundation", domain: "DATA_AI", reusable: true, multiIndustry: true, active: true },
  { key: "lakehouse-warehouse", name: "Data Lakehouse & Warehouse", domain: "DATA_AI", reusable: true, multiIndustry: true, active: true },

  { key: "redis-cache", name: "Redis Cache Foundation", domain: "RUNTIME_INTEGRATION", reusable: true, multiIndustry: true, active: true },
  { key: "background-jobs", name: "Queue & Background Jobs", domain: "RUNTIME_INTEGRATION", reusable: true, multiIndustry: true, active: true },
  { key: "message-broker", name: "Message Broker & Event Bus", domain: "RUNTIME_INTEGRATION", reusable: true, multiIndustry: true, active: true },
  { key: "workflow-orchestration", name: "Workflow Orchestration", domain: "RUNTIME_INTEGRATION", reusable: true, multiIndustry: true, active: true },
  { key: "scheduler", name: "Scheduler Foundation", domain: "RUNTIME_INTEGRATION", reusable: true, multiIndustry: true, active: true },
  { key: "distributed-locking", name: "Distributed Locking", domain: "RUNTIME_INTEGRATION", reusable: true, multiIndustry: true, active: true },
  { key: "idempotency", name: "Idempotency Engine", domain: "RUNTIME_INTEGRATION", reusable: true, multiIndustry: true, active: true },
  { key: "saga-compensation", name: "Saga & Compensation Engine", domain: "RUNTIME_INTEGRATION", reusable: true, multiIndustry: true, active: true },
  { key: "retry-dead-letter", name: "Retry & Dead Letter Queue", domain: "RUNTIME_INTEGRATION", reusable: true, multiIndustry: true, active: true },
  { key: "service-discovery", name: "Service Discovery", domain: "RUNTIME_INTEGRATION", reusable: true, multiIndustry: true, active: true },
  { key: "configuration-registry", name: "Configuration Registry", domain: "RUNTIME_INTEGRATION", reusable: true, multiIndustry: true, active: true },
  { key: "secrets-management", name: "Secrets Management", domain: "RUNTIME_INTEGRATION", reusable: true, multiIndustry: true, active: true },
  { key: "feature-flags", name: "Feature Flags", domain: "RUNTIME_INTEGRATION", reusable: true, multiIndustry: true, active: true },
  { key: "backup-dr-runtime", name: "Backup & Disaster Recovery Runtime", domain: "RUNTIME_INTEGRATION", reusable: true, multiIndustry: true, active: true },

  { key: "central-iam", name: "Central IAM", domain: "IDENTITY_MULTI_TENANCY", reusable: true, multiIndustry: true, active: true },
  { key: "tenant-isolation", name: "Organization & Tenant Isolation", domain: "IDENTITY_MULTI_TENANCY", reusable: true, multiIndustry: true, active: true },
  { key: "sso", name: "Single Sign-On", domain: "IDENTITY_MULTI_TENANCY", reusable: true, multiIndustry: true, active: true },
  { key: "identity-federation", name: "Identity Federation", domain: "IDENTITY_MULTI_TENANCY", reusable: true, multiIndustry: true, active: true },
  { key: "mfa", name: "Multi-Factor Authentication", domain: "IDENTITY_MULTI_TENANCY", reusable: true, multiIndustry: true, active: true },
  { key: "service-accounts", name: "Service Accounts", domain: "IDENTITY_MULTI_TENANCY", reusable: true, multiIndustry: true, active: true },
  { key: "machine-auth", name: "Machine-to-Machine Authentication", domain: "IDENTITY_MULTI_TENANCY", reusable: true, multiIndustry: true, active: true },
  { key: "delegated-authority", name: "Delegated Authority", domain: "IDENTITY_MULTI_TENANCY", reusable: true, multiIndustry: true, active: true },
  { key: "rbac-abac", name: "Fine-Grained RBAC & ABAC", domain: "IDENTITY_MULTI_TENANCY", reusable: true, multiIndustry: true, active: true },
  { key: "consent-management", name: "Consent Management", domain: "IDENTITY_MULTI_TENANCY", reusable: true, multiIndustry: true, active: true },
  { key: "privacy-preferences", name: "Privacy Preferences", domain: "IDENTITY_MULTI_TENANCY", reusable: true, multiIndustry: true, active: true },
  { key: "data-residency-policy", name: "Data Residency Policies", domain: "IDENTITY_MULTI_TENANCY", reusable: true, multiIndustry: true, active: true },

  { key: "api-gateway", name: "Public API Gateway", domain: "DEVELOPER_API_PLUGIN", reusable: true, multiIndustry: true, active: true },
  { key: "api-versioning", name: "API Versioning", domain: "DEVELOPER_API_PLUGIN", reusable: true, multiIndustry: true, active: true },
  { key: "sdk-platform", name: "SDK Platform", domain: "DEVELOPER_API_PLUGIN", reusable: true, multiIndustry: true, active: true },
  { key: "integration-hub", name: "Integration Hub", domain: "DEVELOPER_API_PLUGIN", reusable: true, multiIndustry: true, active: true },
  { key: "webhook-management", name: "Webhook Management", domain: "DEVELOPER_API_PLUGIN", reusable: true, multiIndustry: true, active: true },
  { key: "connector-framework", name: "Connector Framework", domain: "DEVELOPER_API_PLUGIN", reusable: true, multiIndustry: true, active: true },
  { key: "plugin-system", name: "Plugin System", domain: "DEVELOPER_API_PLUGIN", reusable: true, multiIndustry: true, active: true },
  { key: "blueprint-marketplace", name: "Blueprint Marketplace", domain: "DEVELOPER_API_PLUGIN", reusable: true, multiIndustry: true, active: true },
  { key: "developer-portal", name: "Developer Portal", domain: "DEVELOPER_API_PLUGIN", reusable: true, multiIndustry: true, active: true },
  { key: "sandbox", name: "Sandbox Environment", domain: "DEVELOPER_API_PLUGIN", reusable: true, multiIndustry: true, active: true },
  { key: "api-metering", name: "API Usage Metering", domain: "DEVELOPER_API_PLUGIN", reusable: true, multiIndustry: true, active: true },
  { key: "partner-certification", name: "Partner Certification", domain: "DEVELOPER_API_PLUGIN", reusable: true, multiIndustry: true, active: true },

  { key: "legal-entity-registry", name: "Legal Entity Registry", domain: "LEGAL_GLOBAL_OPERATIONS", reusable: true, multiIndustry: true, active: true },
  { key: "jurisdiction-registry", name: "Jurisdiction Registry", domain: "LEGAL_GLOBAL_OPERATIONS", reusable: true, multiIndustry: true, active: true },
  { key: "regulation-versioning", name: "Regulation Versioning", domain: "LEGAL_GLOBAL_OPERATIONS", reusable: true, multiIndustry: true, active: true },
  { key: "dynamic-regulation-engine", name: "Dynamic Regulation Engine", domain: "LEGAL_GLOBAL_OPERATIONS", reusable: true, multiIndustry: true, active: true },
  { key: "contract-policy-engine", name: "Contract Policy Engine", domain: "LEGAL_GLOBAL_OPERATIONS", reusable: true, multiIndustry: true, active: true },
  { key: "data-retention", name: "Data Retention Policies", domain: "LEGAL_GLOBAL_OPERATIONS", reusable: true, multiIndustry: true, active: true },
  { key: "evidence-vault", name: "Evidence Vault", domain: "LEGAL_GLOBAL_OPERATIONS", reusable: true, multiIndustry: true, active: true },
  { key: "legal-hold", name: "Legal Hold", domain: "LEGAL_GLOBAL_OPERATIONS", reusable: true, multiIndustry: true, active: true },
  { key: "esign-governance", name: "E-Signature Governance", domain: "LEGAL_GLOBAL_OPERATIONS", reusable: true, multiIndustry: true, active: true },
  { key: "uae-regulatory-baseline", name: "UAE Regulatory Baseline", domain: "LEGAL_GLOBAL_OPERATIONS", reusable: true, multiIndustry: true, active: true },
  { key: "global-regulatory-packs", name: "Global Regulatory Packs", domain: "LEGAL_GLOBAL_OPERATIONS", reusable: true, multiIndustry: true, active: true },
  { key: "standards-certification", name: "Standards & Certification Framework", domain: "LEGAL_GLOBAL_OPERATIONS", reusable: true, multiIndustry: true, active: true },
  { key: "multi-country-localization", name: "Multi-Country & Localization", domain: "LEGAL_GLOBAL_OPERATIONS", reusable: true, multiIndustry: true, active: true },
  { key: "multi-currency-timezone", name: "Multi-Currency & Multi-Time-Zone", domain: "LEGAL_GLOBAL_OPERATIONS", reusable: true, multiIndustry: true, active: true },
  { key: "regional-configuration", name: "Regional Configuration", domain: "LEGAL_GLOBAL_OPERATIONS", reusable: true, multiIndustry: true, active: true },
  { key: "global-operations-command", name: "Global Operations Command Center", domain: "LEGAL_GLOBAL_OPERATIONS", reusable: true, multiIndustry: true, active: true },

  { key: "central-observability", name: "Logs, Metrics & Traces", domain: "SECURITY_OBSERVABILITY_EXPERIENCE", reusable: true, multiIndustry: true, active: true },
  { key: "audit-evidence-chain", name: "Audit Evidence Chain", domain: "SECURITY_OBSERVABILITY_EXPERIENCE", reusable: true, multiIndustry: true, active: true },
  { key: "soc-siem", name: "SOC & SIEM Integration", domain: "SECURITY_OBSERVABILITY_EXPERIENCE", reusable: true, multiIndustry: true, active: true },
  { key: "vulnerability-management", name: "Vulnerability Management", domain: "SECURITY_OBSERVABILITY_EXPERIENCE", reusable: true, multiIndustry: true, active: true },
  { key: "waf-ddos", name: "WAF & DDoS Protection", domain: "SECURITY_OBSERVABILITY_EXPERIENCE", reusable: true, multiIndustry: true, active: true },
  { key: "threat-detection", name: "Threat Detection", domain: "SECURITY_OBSERVABILITY_EXPERIENCE", reusable: true, multiIndustry: true, active: true },
  { key: "incident-management", name: "Incident Management", domain: "SECURITY_OBSERVABILITY_EXPERIENCE", reusable: true, multiIndustry: true, active: true },
  { key: "security-posture", name: "Security Posture Scoring", domain: "SECURITY_OBSERVABILITY_EXPERIENCE", reusable: true, multiIndustry: true, active: true },
  { key: "ai-security-monitoring", name: "AI Security Monitoring", domain: "SECURITY_OBSERVABILITY_EXPERIENCE", reusable: true, multiIndustry: true, active: true },
  { key: "slo-sla-monitoring", name: "SLO & SLA Monitoring", domain: "SECURITY_OBSERVABILITY_EXPERIENCE", reusable: true, multiIndustry: true, active: true },
  { key: "cost-observability", name: "Cost Observability & FinOps", domain: "SECURITY_OBSERVABILITY_EXPERIENCE", reusable: true, multiIndustry: true, active: true },
  { key: "localization-accessibility", name: "Localization & Accessibility", domain: "SECURITY_OBSERVABILITY_EXPERIENCE", reusable: true, multiIndustry: true, active: true },
  { key: "deaf-accessibility", name: "Deaf Accessibility", domain: "SECURITY_OBSERVABILITY_EXPERIENCE", reusable: true, multiIndustry: true, active: true },
  { key: "voice-os-search", name: "Voice OS & Voice Search", domain: "SECURITY_OBSERVABILITY_EXPERIENCE", reusable: true, multiIndustry: true, active: true },
  { key: "digital-human", name: "Digital Human Foundation", domain: "SECURITY_OBSERVABILITY_EXPERIENCE", reusable: true, multiIndustry: true, active: true },
  { key: "unified-design-system", name: "Unified Design System", domain: "SECURITY_OBSERVABILITY_EXPERIENCE", reusable: true, multiIndustry: true, active: true },
  { key: "experience-composer-ai", name: "Experience Composer AI", domain: "SECURITY_OBSERVABILITY_EXPERIENCE", reusable: true, multiIndustry: true, active: true },
  { key: "omnichannel-experience", name: "Omnichannel Experience", domain: "SECURITY_OBSERVABILITY_EXPERIENCE", reusable: true, multiIndustry: true, active: true },
  { key: "notification-intelligence", name: "Notification Intelligence", domain: "SECURITY_OBSERVABILITY_EXPERIENCE", reusable: true, multiIndustry: true, active: true },
];