export const PublisherMetadata = {
  ENGINE: "PublisherEngineV2",
  VERSION: "2.0.0",
  DEFAULT_LANGUAGE: "ar",
  DEFAULT_COUNTRY: "AE",
  MAX_BATCH_SIZE: 100,
  DEFAULT_TIMEOUT_MS: 60000,
  DEFAULT_PRIORITY: "normal",
  DEFAULT_MAX_RETRIES: 3,
  LOCK_TIMEOUT_MINUTES: 10,
  METRICS_WINDOW: 500,
} as const;
