import {
  BadRequestException,
  Injectable,
  NotFoundException,
} from "@nestjs/common";
import { randomUUID } from "node:crypto";
import {
  DocumentationAiStatus,
  DocumentationArtifact,
  DocumentationAssetInput,
  DocumentationJob,
} from "./documentation-ai.types";
import {
  ApproveDocumentationDto,
  GenerateDocumentationDto,
} from "./documentation-ai.dto";
import { DocumentationAutoGovernanceService } from "./documentation-auto-governance.service";
import { DocumentationEvolutionEngineService } from "./documentation-evolution-engine.service";
import { DocumentationImpactAnalysisService } from "./documentation-impact-analysis.service";
import { DocumentationQualityEngineService } from "./documentation-quality-engine.service";
import { DocumentationRecommendationEngineService } from "./documentation-recommendation-engine.service";

@Injectable()
export class DocumentationAiOrchestratorService {
  private readonly jobs = new Map<string, DocumentationJob>();

  constructor(
    private readonly qualityEngine: DocumentationQualityEngineService,
    private readonly recommendationEngine: DocumentationRecommendationEngineService,
    private readonly impactAnalysis: DocumentationImpactAnalysisService,
    private readonly evolutionEngine: DocumentationEvolutionEngineService,
    private readonly governance: DocumentationAutoGovernanceService,
  ) {}

  getStatus(): DocumentationAiStatus {
    const jobs = [...this.jobs.values()];

    return {
      name: "AVOS Documentation Framework â€” Documentation AI",
      version: "ADF-MP5-2.0.0",
      status: "operational",
      foundationFirst: true,
      capabilityFirst: true,
      blueprintDriven: true,
      humanFinalAuthority: true,
      globalComplianceReadinessGate: true,
      metrics: {
        jobs: jobs.length,
        completed: jobs.filter((job) => job.status === "completed").length,
        failed: jobs.filter((job) => job.status === "failed").length,
        awaitingHumanApproval: jobs.filter(
          (job) => job.status === "requires-human-approval",
        ).length,
      },
    };
  }

  listJobs(): DocumentationJob[] {
    return [...this.jobs.values()].sort((a, b) =>
      b.createdAt.localeCompare(a.createdAt),
    );
  }

  getJob(id: string): DocumentationJob {
    const job = this.jobs.get(id);
    if (!job) {
      throw new NotFoundException(`Documentation job not found: ${id}`);
    }
    return job;
  }

  generate(input: GenerateDocumentationDto): DocumentationJob {
    const objective = input.objective?.trim();
    if (!objective) {
      throw new BadRequestException("objective is required");
    }

    const assets = (input.assets ?? []).map((asset) => this.normalizeAsset(asset));
    if (assets.length === 0) {
      throw new BadRequestException("At least one documentation asset is required");
    }

    const qualityReports = assets.map((asset) => this.qualityEngine.evaluate(asset));
    const governanceDecisions = assets.map((asset, index) =>
      this.governance.decide(
        asset,
        qualityReports[index],
        input.requireHumanApproval !== false,
      ),
    );

    const details = assets.map((asset, index) => {
      const quality = qualityReports[index];
      const recommendations = this.recommendationEngine.recommend(quality);
      const impact = this.impactAnalysis.analyze(asset);
      const evolution = this.evolutionEngine.evolve(asset, quality);

      return [
        `## ${asset.title || asset.name}`,
        "",
        `- Version: ${asset.version || "0.0.0"}`,
        `- Type: ${asset.type || "other"}`,
        `- Quality score: ${quality.score}`,
        `- Governance: ${governanceDecisions[index].decision}`,
        `- Impact risk: ${impact.riskLevel}`,
        `- Proposed next version: ${evolution.toVersion}`,
        "",
        "### Recommendations",
        ...recommendations.map((item) => `- ${item}`),
        "",
        "### Source",
        "```",
        asset.content.slice(0, 5000),
        "```",
      ].join("\n");
    });

    const artifact: DocumentationArtifact = {
      id: `documentation-artifact:${randomUUID()}`,
      title: objective,
      format: "markdown",
      content: [
        `# ${objective}`,
        "",
        "Generated by AVOS Documentation AI MP5.",
        "",
        "## Architectural Guarantees",
        "- Foundation First",
        "- Capability First",
        "- Blueprint Driven",
        "- Human Final Authority",
        "- Global Compliance Readiness Gate",
        "",
        ...details,
      ].join("\n"),
      generatedAt: new Date().toISOString(),
    };

    const requiresHumanApproval = governanceDecisions.some(
      (decision) => decision.requiresHumanApproval,
    );

    const now = new Date().toISOString();
    const job: DocumentationJob = {
      id: `documentation-job:${randomUUID()}`,
      objective,
      status: requiresHumanApproval ? "requires-human-approval" : "completed",
      assets,
      artifacts: [artifact],
      qualityReports,
      governanceDecisions,
      confidence: Number(
        (
          qualityReports.reduce((total, report) => total + report.score, 0) /
          qualityReports.length /
          100
        ).toFixed(2),
      ),
      requiresHumanApproval,
      humanFinalAuthority: true,
      globalComplianceReadinessGate: true,
      createdAt: now,
      updatedAt: now,
    };

    this.jobs.set(job.id, job);
    return job;
  }

  approve(id: string, input: ApproveDocumentationDto): DocumentationJob {
    const approvedBy = input.approvedBy?.trim();
    if (!approvedBy) {
      throw new BadRequestException("approvedBy is required");
    }

    const job = this.getJob(id);
    const approvalArtifact: DocumentationArtifact = {
      id: `documentation-artifact:${randomUUID()}`,
      title: "Human Approval Record",
      format: "markdown",
      content: [
        "# Human Approval",
        "",
        `- Approved by: ${approvedBy}`,
        `- Approved at: ${new Date().toISOString()}`,
        `- Notes: ${input.notes?.trim() || "No notes"}`,
      ].join("\n"),
      generatedAt: new Date().toISOString(),
    };

    const approvedAt = new Date().toISOString();
    const approvalNotes = input.notes?.trim() || "No notes";

    const updated: DocumentationJob = {
      ...job,
      status: "completed",
      requiresHumanApproval: false,
      governanceDecisions: job.governanceDecisions.map((decision) => ({
        ...decision,
        status: "human-approved",
        requiresHumanApproval: false,
        humanApproved: true,
        approvedBy,
        approvedAt,
        approvalNotes,
      })),
      artifacts: [...job.artifacts, approvalArtifact],
      updatedAt: approvedAt,
    };

    this.jobs.set(id, updated);
    return updated;
  }

  remove(id: string): { removed: true; id: string } {
    this.getJob(id);
    this.jobs.delete(id);
    return { removed: true, id };
  }

  private normalizeAsset(asset: DocumentationAssetInput): DocumentationAssetInput {
    const name = asset.name?.trim();
    const content = asset.content?.trim();

    if (!name || !content) {
      throw new BadRequestException("Each asset requires name and content");
    }

    return {
      ...asset,
      id: asset.id || `documentation-asset:${randomUUID()}`,
      name,
      content,
      title: asset.title?.trim() || name,
      version: asset.version?.trim() || "0.0.0",
      type: asset.type || "other",
      dependencies: asset.dependencies ?? [],
      tags: asset.tags ?? [],
    };
  }
}