export const GOVERNMENT_PLATFORM_VERSION = "1.0.0";
export const GOVERNMENT_DEFAULT_TIMEOUT_MS = 12000;
export const GOVERNMENT_DEFAULT_RETRY_LIMIT = 3;
export const GOVERNMENT_DEFAULT_ENVIRONMENT = "SANDBOX";
