import { StrategicCapabilityDefinition } from "./strategic-foundation.types";

export const STRATEGIC_FOUNDATION_CAPABILITIES: StrategicCapabilityDefinition[] = [
  {
    key: "shared-core-foundation",
    name: "Shared Core Foundation",
    domain: "CORE_PLATFORM",
    reusable: true,
    multiIndustry: true,
    constitutionalAlignment: ["TECHNICAL"],
    status: "ACTIVE",
  },
  {
    key: "multi-industry-architecture",
    name: "Multi-Industry Architecture",
    domain: "CORE_PLATFORM",
    reusable: true,
    multiIndustry: true,
    constitutionalAlignment: ["TECHNICAL"],
    status: "ACTIVE",
  },
  {
    key: "shared-business-capabilities",
    name: "Shared Business Capabilities",
    domain: "CORE_PLATFORM",
    reusable: true,
    multiIndustry: true,
    constitutionalAlignment: ["TECHNICAL", "BUSINESS"],
    status: "ACTIVE",
  },
  {
    key: "platform-industry-capability-registries",
    name: "Platform, Industry & Capability Registries",
    domain: "CORE_PLATFORM",
    reusable: true,
    multiIndustry: true,
    constitutionalAlignment: ["TECHNICAL"],
    status: "ACTIVE",
  },
  {
    key: "commerce-lead-deal-revenue",
    name: "Commerce, Lead-to-Deal & Revenue",
    domain: "BUSINESS",
    reusable: true,
    multiIndustry: true,
    constitutionalAlignment: ["BUSINESS"],
    status: "ACTIVE",
  },
  {
    key: "revenue-protection-partner-management",
    name: "Revenue Protection & Partner Management",
    domain: "BUSINESS",
    reusable: true,
    multiIndustry: true,
    constitutionalAlignment: ["BUSINESS", "TRUST"],
    status: "ACTIVE",
  },
  {
    key: "audit-tracking",
    name: "Audit & Tracking",
    domain: "BUSINESS",
    reusable: true,
    multiIndustry: true,
    constitutionalAlignment: ["BUSINESS", "TRUST"],
    status: "ACTIVE",
  },
  {
    key: "permissions-governance-constitution",
    name: "Permissions, Governance & Constitution",
    domain: "GOVERNANCE",
    reusable: true,
    multiIndustry: true,
    constitutionalAlignment: ["EXECUTIVE", "TRUST"],
    status: "ACTIVE",
  },
  {
    key: "event-compliance-foundation",
    name: "Event Tracking & Compliance",
    domain: "GOVERNANCE",
    reusable: true,
    multiIndustry: true,
    constitutionalAlignment: ["TRUST"],
    status: "ACTIVE",
  },
  {
    key: "executive-command-foundation",
    name: "Command Center & Executive Dashboard",
    domain: "EXECUTIVE",
    reusable: true,
    multiIndustry: true,
    constitutionalAlignment: ["EXECUTIVE"],
    status: "ACTIVE",
  },
  {
    key: "owner-ai-presidential-office-board-ai",
    name: "Owner AI, Presidential Office & Board AI",
    domain: "EXECUTIVE",
    reusable: true,
    multiIndustry: true,
    constitutionalAlignment: ["EXECUTIVE"],
    status: "ACTIVE",
  },
  {
    key: "growth-organic-referral-viral",
    name: "Growth, Organic, Referral & Viral Foundations",
    domain: "GROWTH",
    reusable: true,
    multiIndustry: true,
    constitutionalAlignment: ["GROWTH"],
    status: "ACTIVE",
  },
  {
    key: "community-partnership-foundation",
    name: "Community & Partnership Foundation",
    domain: "GROWTH",
    reusable: true,
    multiIndustry: true,
    constitutionalAlignment: ["GROWTH", "TRUST"],
    status: "ACTIVE",
  },
  {
    key: "identity-reputation-antifraud",
    name: "Identity, Reputation & Anti-Fraud",
    domain: "TRUST",
    reusable: true,
    multiIndustry: true,
    constitutionalAlignment: ["TRUST"],
    status: "ACTIVE",
  },
  {
    key: "privacy-security-disputes",
    name: "Privacy, Security & Dispute Management",
    domain: "TRUST",
    reusable: true,
    multiIndustry: true,
    constitutionalAlignment: ["TRUST"],
    status: "ACTIVE",
  },
];

export const STRATEGIC_PLATFORM_REGISTRY = [
  "AVOS Enterprise Core",
  "AVOS Industry Platform",
  "AVOS Commerce & Revenue",
  "AVOS Operations",
  "AVOS Customer & Growth",
  "AVOS Trust & Governance",
  "AVOS Executive Intelligence",
] as const;

export const STRATEGIC_INDUSTRY_REGISTRY = [
  "cars",
  "motorcycles",
  "buggy",
  "heavy-equipment",
  "marine",
  "aviation",
  "camping",
  "trucks",
  "buses",
  "caravans",
] as const;