export const INDUSTRY_SERVICES_COMPONENTS = [
  "service-booking-engine",
  "workshop-management",
  "technician-scheduling",
  "maintenance-plans",
  "preventive-maintenance",
  "repair-orders",
  "service-history",
  "digital-service-records",
  "inspection-engine",
  "ai-inspection-workflow",
  "condition-reports",
  "photo-video-evidence",
  "inspection-certificates",
  "warranty-management",
  "extended-warranty",
  "warranty-claims",
  "claim-approval-workflow",
  "parts-catalog",
  "parts-inventory",
  "parts-ordering",
  "supplier-integration",
  "parts-pricing",
  "accessories-marketplace",
  "bundle-builder",
  "installation-services",
  "mobile-service",
  "roadside-assistance",
  "vehicle-pickup-delivery",
] as const;

export const SUPPORTED_SERVICE_INDUSTRIES = [
  "cars",
  "motorcycles",
  "buggy",
  "heavy-equipment",
  "marine",
  "aviation",
  "camping",
  "trucks",
  "buses",
  "caravans",
] as const;