import { F5Capability } from "./enterprise-ultimate-f5.types";

export const F5_CAPABILITIES: Record<F5Capability, string> = {
  AVOS_SMART_WORKSPACE: "AVOS Smart Workspace",
  AVOS_LIVE_COMMAND: "AVOS Live Command",
  AVOS_COCKPIT: "AVOS Cockpit",
  AVOS_STORY_MODE: "AVOS Story Mode",
  AVOS_BUSINESS_PULSE: "AVOS Business Pulse",
  AVOS_AI_INBOX: "AVOS AI Inbox",
  AVOS_DAILY_MISSION: "AVOS Daily Mission",
  AVOS_LIVE_ACTIVITY_FEED: "AVOS Live Activity Feed",
  AVOS_OFFICE_VIEW: "AVOS Office View",
  DIGITAL_EMPLOYEES: "Digital Employees",
  SALES_MANAGER_AI: "Sales Manager AI",
  FINANCE_MANAGER_AI: "Finance Manager AI",
  MARKETING_MANAGER_AI: "Marketing Manager AI",
  INVENTORY_MANAGER_AI: "Inventory Manager AI",
  CEO_ADVISOR_AI: "CEO Advisor AI",
  AI_DAILY_BRIEFING: "AI Daily Briefing",
  AI_ONE_CLICK: "AI One Click",
  ROLE_BASED_DASHBOARDS: "Role-Based Dashboards",
  CUSTOMIZABLE_DASHBOARD_LAYOUTS: "Customizable Dashboard Layouts",
  ADVERTISEMENT_ANALYTICS_WIDGETS: "Advertisement Analytics Widgets",
  VEHICLE_360_WORKSPACE: "Vehicle 360 Workspace",
  CUSTOMER_360_WORKSPACE: "Customer 360 Workspace",
  DEALER_360_WORKSPACE: "Dealer 360 Workspace",
  MARKET_360_WORKSPACE: "Market 360 Workspace",
  AI_360_WORKSPACE: "AI 360 Workspace",
  UNIFIED_TIMELINE: "Unified Timeline",
  MISSION_CONTROL: "Mission Control",
  COMMAND_PALETTE: "Command Palette",
  GLOBAL_SEARCH_WORKSPACE: "Global Search Workspace",
  WORKSPACE_PERSONALIZATION: "Workspace Personalization",
};