export const LAUNCH_READINESS_CAPABILITIES = [
  "pricing-plan-management",
  "subscription-lifecycle",
  "trial-management",
  "seat-management",
  "subscription-billing",
  "invoice-generation",
  "tax-calculation",
  "plan-upgrade-downgrade",
  "tenant-activation",
  "sandbox-readiness",
  "staging-readiness",
  "production-readiness",
  "launch-checklist",
  "launch-blocker-management",
  "legal-readiness",
  "security-readiness",
  "operations-readiness",
  "support-readiness",
  "support-case-management",
  "sla-monitoring",
  "customer-onboarding",
  "product-adoption",
  "launch-kpis",
  "revenue-kpis",
  "retention-kpis",
  "executive-launch-dashboard",
] as const;

export const DEFAULT_LAUNCH_CHECKLIST = [
  { key: "product-core-flows", name: "Core product flows verified", category: "PRODUCT", required: true },
  { key: "typescript-build", name: "TypeScript and build pass", category: "TECHNICAL", required: true },
  { key: "flutter-analyze", name: "Flutter analyze pass", category: "TECHNICAL", required: true },
  { key: "security-baseline", name: "Security baseline approved", category: "SECURITY", required: true },
  { key: "privacy-terms", name: "Privacy and terms approved", category: "LEGAL", required: true },
  { key: "billing-ready", name: "Billing and pricing configured", category: "COMMERCIAL", required: true },
  { key: "support-ready", name: "Support operations ready", category: "SUPPORT", required: true },
  { key: "monitoring-ready", name: "Monitoring and alerts ready", category: "OPERATIONS", required: true },
] as const;