export const LIVE_AUCTION_CAPABILITIES = [
  "live-auction-engine",
  "real-time-bidding-engine",
  "automatic-bid-increment",
  "reserve-price-engine",
  "buy-now",
  "proxy-bidding",
  "auction-scheduling",
  "countdown-engine",
  "auction-moderation",
  "winner-selection",
  "payment-lock",
  "anti-sniping-engine",
  "bid-history",
  "auction-analytics",
  "fraud-detection",
  "ai-auction-recommendations",
  "dealer-auctions",
  "public-auctions",
  "private-auctions",
  "multi-industry-auctions",
] as const;