import {
  GenesisV3Artifact,
  GenesisV3ArtifactKind,
  GenesisV3Domain,
} from "./contracts";
import { GenesisV3ArtifactFactory } from "./artifact-factory";
import { kebab, pascal } from "./name-utils";

export class GenesisV3FrontendGenerator {
  constructor(readonly factory = new GenesisV3ArtifactFactory()) {}

  generate(
    title: string,
    domains: readonly GenesisV3Domain[],
  ): GenesisV3Artifact[] {
    const cards = domains
      .map(
        (domain) =>
          `<a className="card" href="/${kebab(domain.key)}">${pascal(domain.entityName)}</a>`,
      )
      .join("\n        ");

    return [
      this.factory.create(
        "apps/web/app/page.tsx",
        GenesisV3ArtifactKind.FRONTEND,
        `export default function HomePage() {
  return (
    <main>
      <h1>${title}</h1>
      <p>Generated by AVOS Genesis Engine v3.</p>
      <section>
        ${cards}
      </section>
    </main>
  );
}`,
        { domains: domains.length },
      ),
      this.factory.create(
        "apps/web/app/layout.tsx",
        GenesisV3ArtifactKind.FRONTEND,
        `export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}`,
      ),
      this.factory.create(
        "apps/web/package.json",
        GenesisV3ArtifactKind.CONFIG,
        JSON.stringify(
          {
            name: "avos-generated-web",
            private: true,
            scripts: {
              dev: "next dev",
              build: "next build",
              start: "next start"
            },
            dependencies: {
              next: "latest",
              react: "latest",
              "react-dom": "latest"
            }
          },
          null,
          2,
        ),
      ),
    ];
  }
}
