import {
  GenesisV3Artifact,
  GenesisV3ArtifactKind,
  GenesisV3Specification,
} from "./contracts";
import { GenesisV3ArtifactFactory } from "./artifact-factory";

export class GenesisV3PlatformGenerator {
  constructor(readonly factory = new GenesisV3ArtifactFactory()) {}

  generate(spec: GenesisV3Specification): GenesisV3Artifact[] {
    const artifacts: GenesisV3Artifact[] = [
      this.factory.create(
        "package.json",
        GenesisV3ArtifactKind.CONFIG,
        JSON.stringify(
          {
            name: spec.systemKey,
            private: true,
            workspaces: ["apps/*"],
            scripts: {
              build: "echo build generated system",
              test: "echo test generated system",
              lint: "echo lint generated system",
              smoke: "echo smoke generated system"
            }
          },
          null,
          2,
        ),
      ),
      this.factory.create(
        ".env.example",
        GenesisV3ArtifactKind.CONFIG,
        `DATABASE_URL="postgresql://user:password@localhost:5432/${spec.systemKey}"
PORT=3000
NODE_ENV=development`,
      ),
      this.factory.create(
        "README.md",
        GenesisV3ArtifactKind.DOCUMENTATION,
        `# ${spec.systemName}

${spec.description}

Generated by AVOS Genesis Engine v3.

## Domains

${spec.domains.map((domain) => `- ${domain.key}`).join("\n")}

## Architecture

- Backend: NestJS-compatible TypeScript structure
- Database: Prisma
- Frontend: Next.js shell
- CI: ${spec.ci ? "enabled" : "disabled"}
- Docker: ${spec.docker ? "enabled" : "disabled"}
`,
      ),
      this.factory.create(
        "registrations/enterprise-brain.json",
        GenesisV3ArtifactKind.REGISTRATION,
        JSON.stringify(
          {
            systemKey: spec.systemKey,
            systemName: spec.systemName,
            capabilities: spec.domains.map((domain) => domain.key),
            source: "genesis-engine-v3",
          },
          null,
          2,
        ),
      ),
      this.factory.create(
        "registrations/evolution-center.json",
        GenesisV3ArtifactKind.REGISTRATION,
        JSON.stringify(
          {
            systemKey: spec.systemKey,
            baselineVersion: "1.0.0",
            modules: spec.domains.length,
            healthThreshold: 80,
          },
          null,
          2,
        ),
      ),
      this.factory.create(
        "registrations/blueprint-registry.json",
        GenesisV3ArtifactKind.REGISTRATION,
        JSON.stringify(
          {
            systemKey: spec.systemKey,
            blueprint: "genesis-v3-first-real-system",
            version: "1.0.0",
            domains: spec.domains.map((domain) => domain.key),
          },
          null,
          2,
        ),
      ),
    ];

    if (spec.docker) {
      artifacts.push(
        this.factory.create(
          "Dockerfile",
          GenesisV3ArtifactKind.DOCKER,
          `FROM node:22-alpine
WORKDIR /app
COPY . .
RUN npm install
CMD ["npm", "run", "build"]`,
        ),
        this.factory.create(
          "docker-compose.yml",
          GenesisV3ArtifactKind.DOCKER,
          `services:
  app:
    build: .
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/${spec.systemKey}
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ${spec.systemKey}
`,
        ),
      );
    }

    if (spec.ci) {
      artifacts.push(
        this.factory.create(
          ".github/workflows/ci.yml",
          GenesisV3ArtifactKind.CI,
          `name: CI

on:
  push:
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm install
      - run: npm run build
      - run: npm run test
      - run: npm run lint
`,
        ),
      );
    }

    return artifacts;
  }
}
