$ErrorActionPreference = "Stop"

$Root = Resolve-Path (Join-Path $PSScriptRoot "..")
Set-Location $Root

$SmokeFile = Join-Path $env:TEMP "avos-genesis-engine-v3-first-system-smoke.cjs"

@'
const {
  GenesisV3FirstSystemOrchestrator,
  GenesisV3RuntimeVerifier,
} = require(process.cwd() + "/dist/genesis-engine-v3-first-system");

const orchestrator = new GenesisV3FirstSystemOrchestrator();

const result = orchestrator.execute({
  systemKey: "avos-first-real-system",
  systemName: "AVOS First Real System",
  description: "First real full-stack system generated by AVOS Genesis Engine v3.",
  domains: [
    {
      key: "customers",
      entityName: "Customer",
      fields: [
        { name: "name", type: "string", required: true },
        { name: "email", type: "string", required: true, unique: true },
        { name: "active", type: "boolean", required: true }
      ]
    },
    {
      key: "orders",
      entityName: "Order",
      fields: [
        { name: "reference", type: "string", required: true, unique: true },
        { name: "total", type: "number", required: true },
        { name: "createdOn", type: "date", required: true }
      ]
    }
  ],
  frontend: {
    enabled: true,
    title: "AVOS First Real System"
  },
  database: {
    provider: "postgresql"
  },
  docker: true,
  ci: true
});

const health = new GenesisV3RuntimeVerifier().verify(result);

if (!health.healthy) {
  console.error(JSON.stringify({ result, health }, null, 2));
  process.exit(1);
}

console.log(JSON.stringify({
  success: true,
  system: "AVOS Genesis Engine",
  bundle: "Genesis Engine v3 First Real System",
  version: "3.0.0",
  status: result.status,
  score: health.score,
  totalFiles: health.totalFiles,
  backendFiles: health.backendFiles,
  prismaFiles: health.prismaFiles,
  frontendFiles: health.frontendFiles,
  dockerFiles: health.dockerFiles,
  ciFiles: health.ciFiles,
  documentationFiles: health.documentationFiles,
  registrationFiles: health.registrationFiles,
  completionPercent: health.completionPercent,
  healthStatus: "healthy"
}, null, 2));
'@ | Set-Content `
    -Path $SmokeFile `
    -Encoding UTF8

try {
    node $SmokeFile

    if ($LASTEXITCODE -ne 0) {
        throw "Genesis Engine v3 First Real System smoke test failed."
    }
}
finally {
    Remove-Item $SmokeFile -Force -ErrorAction SilentlyContinue
}
