import { CommercialLaunchCapability } from "./commercial-launch.types";

export const COMMERCIAL_LAUNCH_CAPABILITIES: CommercialLaunchCapability[] = [
  { key: "commercial-launch-center", name: "Commercial Launch Center", enabled: true },
  { key: "multi-tenant-management", name: "Multi-Tenant Enterprise Management", enabled: true },
  { key: "user-role-management", name: "User & Role Management", enabled: true },
  { key: "identity-sso-mfa", name: "Identity / SSO / MFA", enabled: true },
  { key: "subscription-activation", name: "Real Subscription Activation", enabled: true },
  { key: "revenue-operations-center", name: "Revenue Operations Center", enabled: true },
  { key: "executive-business-dashboard", name: "Executive Business Dashboard", enabled: true },
  { key: "business-intelligence-kpis", name: "Business Intelligence & KPIs", enabled: true },
  { key: "ai-operations-center", name: "AI Operations Center", enabled: true },
  { key: "multi-country-currency", name: "Multi-Country / Multi-Currency", enabled: true },
  { key: "multi-language", name: "Multi-Language", enabled: true },
  { key: "mobile-release-center", name: "Mobile Release Center", enabled: true },
  { key: "web-release-center", name: "Web Release Center", enabled: true },
  { key: "app-marketplace", name: "App Marketplace", enabled: true },
  { key: "plugin-marketplace", name: "Plugin Marketplace", enabled: true },
  { key: "partner-onboarding", name: "Partner Onboarding", enabled: true },
  { key: "banking-connections", name: "Banking Connections", enabled: true },
  { key: "insurance-connections", name: "Insurance Connections", enabled: true },
  { key: "export-logistics-connections", name: "Export & Logistics Connections", enabled: true },
  { key: "government-gateway-connections", name: "Government Gateway Connections", enabled: true },
  { key: "marketing-launch-center", name: "Marketing Launch Center", enabled: true },
  { key: "growth-engine", name: "Growth Engine", enabled: true },
  { key: "reputation-reviews", name: "Reputation & Reviews", enabled: true },
  { key: "customer-communication-center", name: "Customer Communication Center", enabled: true },
  { key: "support-ticket-center", name: "Support & Ticket Center", enabled: true },
  { key: "compliance-center", name: "Compliance Center", enabled: true },
  { key: "financial-reporting", name: "Financial Reporting", enabled: true },
  { key: "ai-business-insights", name: "AI Business Insights", enabled: true },
  { key: "live-monitoring-center", name: "Live Monitoring Center", enabled: true },
  { key: "operations-command-center", name: "Operations Command Center", enabled: true }
];