import { G1Capability } from "./enterprise-ultimate-g1.types";

export const G1_CAPABILITIES: Record<G1Capability, string> = {
  GLOBAL_DESIGN_SYSTEM: "Global Design System",
  AVOS_BRAND_RUNTIME: "AVOS Brand Runtime",
  LOGO_SYSTEM: "Logo System",
  LIGHT_THEME_ENGINE: "Light Theme Engine",
  DARK_THEME_ENGINE: "Dark Theme Engine",
  RTL_LTR_ENGINE: "RTL/LTR Engine",
  ARABIC_LOCALIZATION: "Arabic Localization",
  ENGLISH_LOCALIZATION: "English Localization",
  RESPONSIVE_WEB_SHELL: "Responsive Web Shell",
  MOBILE_APP_SHELL: "Mobile App Shell",
  ACCESSIBILITY_ENGINE: "Accessibility Engine",
  GLOBAL_NAVIGATION: "Global Navigation",
  GLOBAL_SEARCH: "Global Search",
  NOTIFICATION_CENTER: "Notification Center",
  PROFILE_CENTER: "Profile Center",
  ONBOARDING_ENGINE: "Onboarding Engine",
  AUTHENTICATION_EXPERIENCE: "Authentication Experience",
  LANDING_EXPERIENCE: "Landing Experience",
  MARKETPLACE_EXPERIENCE: "Marketplace Experience",
  VEHICLE_DETAIL_EXPERIENCE: "Vehicle Detail Experience",
  DEAL_EXPERIENCE: "Deal Experience",
  AUCTION_EXPERIENCE: "Auction Experience",
  CHAT_EXPERIENCE: "Chat Experience",
  AI_ASSISTANT_EXPERIENCE: "AI Assistant Experience",
  ADMIN_EXPERIENCE: "Admin Experience",
  DEALER_EXPERIENCE: "Dealer Experience",
  PARTNER_EXPERIENCE: "Partner Experience",
  DESIGN_TOKENS: "Design Tokens",
  UI_COMPONENT_LIBRARY: "UI Component Library",
  EXPERIENCE_CONFIGURATION_CENTER: "Experience Configuration Center",
};

export const G1_DEFAULT_TOKENS = {
  brandNavy: "#18324A",
  brandGold: "#B8924A",
  surfaceSand: "#EDE5D8",
  surfaceWarm: "#F6F1E8",
  surfaceCard: "#FFFDF8",
  textPrimary: "#1D2A36",
  textSecondary: "#66717C",
  borderSoft: "#D8CDBE",
  success: "#2F7D64",
  warning: "#B77622",
  danger: "#B44A4A",
  radiusCard: 20,
  radiusButton: 14,
};