export const CAPABILITY_INTELLIGENCE_VERSION = "1.0.0";

export const CAPABILITY_INTELLIGENCE_PILLARS = [
  "CAPABILITY_KNOWLEDGE",
  "CAPABILITY_MEMORY",
  "USAGE_ANALYTICS",
  "QUALITY_INDEX",
  "TRUST_SCORE",
  "MATURITY_MODEL",
  "RISK_ASSESSMENT",
  "TECHNICAL_DEBT_DETECTION",
  "DUPLICATE_DETECTION",
  "REUSE_INTELLIGENCE",
  "EVOLUTION_SUGGESTIONS",
  "RECOMMENDATION_ENGINE",
  "HEALTH_TREND_ANALYSIS",
  "PERFORMANCE_INTELLIGENCE",
  "INTELLIGENT_RANKING",
  "CAPABILITY_INSIGHTS_API",
] as const;

export const CAPABILITY_INTELLIGENCE_THRESHOLDS = {
  highRisk: 70,
  lowTrust: 55,
  lowQuality: 60,
  highTechnicalDebt: 65,
  duplicateReview: 0.65,
  duplicateMerge: 0.82,
  strongReuse: 75,
} as const;