export default function exportPage() {
  return (
    <main dir="rtl" className="min-h-screen bg-slate-50 px-6 py-12">
      <div className="mx-auto max-w-7xl">
        <h1 className="text-4xl font-black">التصدير والشحن</h1>
        <p className="mt-3 text-slate-600">Generated by AVOS Web Pack Generator v1.</p>
      </div>
    </main>
  );
}