import { ConstitutionDefinition } from "./constitutional-foundation.types";

export const AVOS_CONSTITUTIONS: ConstitutionDefinition[] = [
  {
    key: "TECHNICAL",
    name: "Technical Constitution",
    version: "1.0.0",
    active: true,
    principles: [
      {
        key: "modular-architecture",
        title: "Modular Architecture",
        description: "All platform capabilities must remain modular and composable.",
        mandatory: true,
      },
      {
        key: "shared-core-platform",
        title: "Shared Core Platform",
        description: "Industries must reuse the shared platform foundation.",
        mandatory: true,
      },
      {
        key: "multi-industry-foundation",
        title: "Multi-Industry Foundation",
        description: "Architecture must be industry-based and reusable.",
        mandatory: true,
      },
      {
        key: "reusable-capabilities",
        title: "Reusable Capabilities",
        description: "Business capabilities must be reusable across industries.",
        mandatory: true,
      },
      {
        key: "minimal-code-duplication",
        title: "Minimal Code Duplication",
        description: "Duplicate implementation must be prevented.",
        mandatory: true,
      },
      {
        key: "scalability-by-design",
        title: "Scalability by Design",
        description: "Every module must support scalable enterprise operation.",
        mandatory: true,
      },
    ],
  },
  {
    key: "BUSINESS",
    name: "Business Constitution",
    version: "1.0.0",
    active: true,
    principles: [
      {
        key: "commerce-engine",
        title: "Commerce Engine",
        description: "All industries must use governed commerce foundations.",
        mandatory: true,
      },
      {
        key: "lead-to-deal-lifecycle",
        title: "Lead-to-Deal Lifecycle",
        description: "Commercial activity must be traceable from lead to deal.",
        mandatory: true,
      },
      {
        key: "revenue-engine",
        title: "Revenue Engine",
        description: "Revenue creation must be measurable and auditable.",
        mandatory: true,
      },
      {
        key: "revenue-protection",
        title: "Revenue Protection",
        description: "Revenue leakage controls are mandatory.",
        mandatory: true,
      },
      {
        key: "multiple-revenue-streams",
        title: "Multiple Revenue Streams",
        description: "Platform monetization must support multiple streams.",
        mandatory: true,
      },
      {
        key: "partner-management",
        title: "Partner Management",
        description: "Partners must be governed through lifecycle controls.",
        mandatory: true,
      },
    ],
  },
  {
    key: "EXECUTIVE",
    name: "Executive Constitution",
    version: "1.0.0",
    active: true,
    principles: [
      {
        key: "command-center-foundation",
        title: "Command Center Foundation",
        description: "Executive command visibility is mandatory.",
        mandatory: true,
      },
      {
        key: "owner-ai-foundation",
        title: "Owner AI Foundation",
        description: "Owner AI may recommend but cannot override human authority.",
        mandatory: true,
      },
      {
        key: "presidential-office-foundation",
        title: "Presidential Office Foundation",
        description: "Strategic coordination must remain governable.",
        mandatory: true,
      },
      {
        key: "board-of-directors-ai",
        title: "Board of Directors AI Foundation",
        description: "Board AI supports analysis and recommendations.",
        mandatory: true,
      },
      {
        key: "governance",
        title: "Governance",
        description: "Governed decision paths are mandatory.",
        mandatory: true,
      },
      {
        key: "permissions",
        title: "Permissions",
        description: "All sensitive actions require permission evaluation.",
        mandatory: true,
      },
      {
        key: "human-final-decision",
        title: "Human Final Decision Authority",
        description: "Humans retain final authority for protected decisions.",
        mandatory: true,
      },
    ],
  },
  {
    key: "GROWTH",
    name: "Growth Constitution",
    version: "1.0.0",
    active: true,
    principles: [
      {
        key: "growth-architecture",
        title: "Growth Architecture",
        description: "Growth is a foundational platform architecture.",
        mandatory: true,
      },
      {
        key: "organic-growth-engine",
        title: "Organic Growth Engine",
        description: "Organic acquisition must be supported.",
        mandatory: true,
      },
      {
        key: "viral-engine",
        title: "Viral Engine",
        description: "Viral distribution mechanisms must be measurable.",
        mandatory: true,
      },
      {
        key: "referral-engine",
        title: "Referral Engine",
        description: "Referral activity must be governed and auditable.",
        mandatory: true,
      },
      {
        key: "creator-economy",
        title: "Creator Economy",
        description: "Creator participation must support governed monetization.",
        mandatory: true,
      },
      {
        key: "community-engine",
        title: "Community Engine",
        description: "Community growth must preserve trust and safety.",
        mandatory: true,
      },
      {
        key: "enterprise-partnership-engine",
        title: "Enterprise Partnership Engine",
        description: "Enterprise growth must use partner governance.",
        mandatory: true,
      },
      {
        key: "ai-growth-brain",
        title: "AI Growth Brain",
        description: "Growth AI recommendations remain policy-controlled.",
        mandatory: true,
      },
      {
        key: "global-expansion-foundation",
        title: "Global Expansion Foundation",
        description: "Expansion must respect regional regulation and trust.",
        mandatory: true,
      },
    ],
  },
  {
    key: "TRUST",
    name: "Trust Constitution",
    version: "1.0.0",
    active: true,
    principles: [
      {
        key: "identity-verification",
        title: "Identity Verification",
        description: "Protected actions require verified identity.",
        mandatory: true,
      },
      {
        key: "trust-reputation",
        title: "Trust & Reputation",
        description: "Trust and reputation signals must be traceable.",
        mandatory: true,
      },
      {
        key: "audit-trail",
        title: "Audit Trail",
        description: "Critical activity must produce immutable audit evidence.",
        mandatory: true,
      },
      {
        key: "anti-fraud",
        title: "Anti-Fraud",
        description: "Fraud detection and response are mandatory.",
        mandatory: true,
      },
      {
        key: "compliance",
        title: "Compliance",
        description: "Applicable policies and regulations must be evaluated.",
        mandatory: true,
      },
      {
        key: "privacy",
        title: "Privacy",
        description: "Personal and enterprise data must be protected.",
        mandatory: true,
      },
      {
        key: "security",
        title: "Security",
        description: "Security controls must protect every platform layer.",
        mandatory: true,
      },
      {
        key: "dispute-management",
        title: "Dispute Management",
        description: "Disputes must use governed and auditable workflows.",
        mandatory: true,
      },
    ],
  },
];