import { Injectable } from "@nestjs/common";
import { ProjectGeneratorRequest, ProjectStructureNode } from "./project-generator.contracts";

@Injectable()
export class ProjectStructureFactoryService {
  createNestJsApi(request: ProjectGeneratorRequest, variables: Record<string, unknown>): ProjectStructureNode[] {
    const slug = String(variables.projectSlug);
    const className = String(variables.projectClassName);
    return [
      { id: "src-dir", kind: "directory", relativePath: "src" },
      { id: "package", kind: "manifest", relativePath: "package.json", content: JSON.stringify({
        name: slug, version: "0.1.0", private: true,
        scripts: { build: "nest build", start: "nest start", "start:dev": "nest start --watch" }
      }, null, 2) + "\n" },
      { id: "main", kind: "source", relativePath: "src/main.ts", dependsOn: ["src-dir"], content: [
        'import { NestFactory } from "@nestjs/core";',
        'import { AppModule } from "./app.module";',
        "",
        "async function bootstrap(): Promise<void> {",
        "  const app = await NestFactory.create(AppModule);",
        "  await app.listen(process.env.PORT ?? 3000);",
        "}",
        "void bootstrap();",
        ""
      ].join("\n") },
      { id: "module", kind: "source", relativePath: "src/app.module.ts", dependsOn: ["src-dir"], content: [
        'import { Module } from "@nestjs/common";',
        "",
        "@Module({})",
        `export class ${className}Module {}`,
        ""
      ].join("\n") },
      { id: "readme", kind: "documentation", relativePath: "README.md", content: [
        `# ${request.name}`, "", request.description ?? "Generated by AVOS Factory.", "",
        "Human Final Authority is preserved.", ""
      ].join("\n") }
    ];
  }

  createNestJsModule(_request: ProjectGeneratorRequest, variables: Record<string, unknown>): ProjectStructureNode[] {
    const slug = String(variables.projectSlug);
    const className = String(variables.projectClassName);
    return [
      { id: "module-dir", kind: "directory", relativePath: `src/${slug}` },
      { id: "module-file", kind: "source", relativePath: `src/${slug}/${slug}.module.ts`, dependsOn: ["module-dir"], content: [
        'import { Module } from "@nestjs/common";', "", "@Module({})", `export class ${className}Module {}`, ""
      ].join("\n") },
      { id: "module-index", kind: "source", relativePath: `src/${slug}/index.ts`, dependsOn: ["module-file"], content: `export * from "./${slug}.module";\n` }
    ];
  }

  createTypeScriptLibrary(request: ProjectGeneratorRequest, variables: Record<string, unknown>): ProjectStructureNode[] {
    const slug = String(variables.projectSlug);
    return [
      { id: "lib-src", kind: "directory", relativePath: "src" },
      { id: "lib-package", kind: "manifest", relativePath: "package.json", content: JSON.stringify({
        name: slug, version: "0.1.0", private: true, main: "dist/index.js", types: "dist/index.d.ts",
        scripts: { build: "tsc -p tsconfig.json" }
      }, null, 2) + "\n" },
      { id: "lib-index", kind: "source", relativePath: "src/index.ts", dependsOn: ["lib-src"], content: [
        `export const projectName = "${request.name}";`,
        'export const generatedBy = "AVOS Factory";',
        "export const humanFinalAuthority = true;",
        ""
      ].join("\n") }
    ];
  }
}
