import { IndustryCode } from "./industry-mega-bundle-3.types";

export const INDUSTRY_CAPABILITIES: Record<IndustryCode, string[]> = {
  INSURANCE: [
    "policy-management",
    "underwriting",
    "claims",
    "pricing",
    "risk-assessment",
    "fraud-detection",
    "reinsurance",
    "broker-management",
    "compliance",
    "insurance-ai",
  ],
  RETAIL_COMMERCE: [
    "catalog",
    "inventory",
    "orders",
    "payments",
    "promotions",
    "loyalty",
    "stores",
    "fulfillment",
    "customer-intelligence",
    "retail-ai",
  ],
  HOSPITALITY: [
    "properties",
    "rooms",
    "reservations",
    "guest-services",
    "housekeeping",
    "food-and-beverage",
    "events",
    "revenue-management",
    "loyalty",
    "hospitality-ai",
  ],
  EDUCATION: [
    "institutions",
    "students",
    "admissions",
    "programs",
    "courses",
    "attendance",
    "assessments",
    "payments",
    "learning-analytics",
    "education-ai",
  ],
  GOVERNMENT: [
    "citizen-registry",
    "digital-services",
    "permits",
    "licenses",
    "case-management",
    "public-payments",
    "grants",
    "inspections",
    "compliance",
    "government-ai",
  ],
};