import { F2Capability } from "./enterprise-ultimate-f2.types";

export const F2_CAPABILITIES: Record<F2Capability, string> = {
  AI_COMMAND_CENTER_V2: "AI Command Center V2",
  ENTERPRISE_DECISION_CENTER: "Enterprise Decision Center",
  EXECUTIVE_DASHBOARD: "Executive Dashboard",
  CEO_WORKSPACE: "CEO Workspace",
  AI_MISSION_CENTER: "AI Mission Center",
  SMART_NOTIFICATION_ENGINE_V2: "Smart Notification Engine V2",
  ENTERPRISE_KPI_DASHBOARD: "Enterprise KPI Dashboard",
  ENTERPRISE_LIVE_TIMELINE: "Enterprise Live Timeline",
  BUSINESS_HEALTH_MONITOR: "Business Health Monitor",
  REVENUE_INTELLIGENCE: "Revenue Intelligence",
  COST_INTELLIGENCE: "Cost Intelligence",
  PROFIT_INTELLIGENCE: "Profit Intelligence",
  CUSTOMER_INTELLIGENCE: "Customer Intelligence",
  VEHICLE_INTELLIGENCE_DASHBOARD: "Vehicle Intelligence Dashboard",
  SALES_INTELLIGENCE_DASHBOARD: "Sales Intelligence Dashboard",
  MARKETING_INTELLIGENCE_DASHBOARD: "Marketing Intelligence Dashboard",
  FINANCE_INTELLIGENCE_DASHBOARD: "Finance Intelligence Dashboard",
  OPERATIONS_INTELLIGENCE_DASHBOARD: "Operations Intelligence Dashboard",
  INVENTORY_INTELLIGENCE_DASHBOARD: "Inventory Intelligence Dashboard",
  RISK_INTELLIGENCE_DASHBOARD: "Risk Intelligence Dashboard",
  ENTERPRISE_AI_INBOX: "Enterprise AI Inbox",
  ENTERPRISE_AI_TASKS: "Enterprise AI Tasks",
  ENTERPRISE_ACTION_CENTER: "Enterprise Action Center",
  EXECUTIVE_REPORTS_ENGINE: "Executive Reports Engine",
  ENTERPRISE_INSIGHTS_ENGINE: "Enterprise Insights Engine",
  STRATEGY_DASHBOARD: "Strategy Dashboard",
  GOAL_TRACKING_ENGINE: "Goal Tracking Engine",
  OKR_DASHBOARD: "OKR Dashboard",
  EXECUTIVE_ANALYTICS: "Executive Analytics",
  LIVE_ENTERPRISE_METRICS: "Live Enterprise Metrics",
};