import { Injectable } from "@nestjs/common";
import { GenerateCapabilityDto } from "../dto/generate-capability.dto";
import { GenerateProjectDto } from "../dto/generate-project.dto";
import { FactoryGenerationEngineService } from "../generation/generation-engine.service";

@Injectable()
export class FactoryCapabilityGeneratorService {
  constructor(
    private readonly generation: FactoryGenerationEngineService,
  ) {}

  generate(dto: GenerateCapabilityDto) {
    const className = this.toPascalCase(dto.capabilityName);
    const slug = this.toSlug(dto.capabilityName);
    const basePath = `src/${slug}`;

    const files: GenerateProjectDto["files"] = [
      {
        path: `${basePath}/${slug}.contracts.ts`,
        type: "source",
        content: `export interface ${className}Request {\n  objective: string;\n  metadata?: Record<string, unknown>;\n}\n\nexport interface ${className}Result {\n  success: boolean;\n  capability: "${slug}";\n  objective: string;\n  executedAt: string;\n}\n`,
      },
      {
        path: `${basePath}/${slug}.service.ts`,
        type: "source",
        content: `import { Injectable } from "@nestjs/common";\nimport { ${className}Request, ${className}Result } from "./${slug}.contracts";\n\n@Injectable()\nexport class ${className}Service {\n  execute(request: ${className}Request): ${className}Result {\n    return {\n      success: true,\n      capability: "${slug}",\n      objective: request.objective,\n      executedAt: new Date().toISOString(),\n    };\n  }\n}\n`,
      },
      {
        path: `${basePath}/${slug}.module.ts`,
        type: "source",
        content: `import { Module } from "@nestjs/common";\n${dto.includeController !== false ? `import { ${className}Controller } from "./${slug}.controller";\n` : ""}import { ${className}Service } from "./${slug}.service";\n\n@Module({\n  providers: [${className}Service],\n  ${dto.includeController !== false ? `controllers: [${className}Controller],\n  ` : ""}exports: [${className}Service],\n})\nexport class ${className}Module {}\n`,
      },
      {
        path: `${basePath}/capability.manifest.json`,
        type: "metadata",
        content: JSON.stringify(
          {
            id: slug,
            name: dto.capabilityName,
            version: dto.version ?? "1.0.0",
            objective: dto.objective,
            lifecycle: "prototype",
            humanFinalAuthority: true,
            generatedBy: "avos-code-factory",
          },
          null,
          2,
        ),
      },
      {
        path: `${basePath}/README.md`,
        type: "documentation",
        content: `# ${dto.capabilityName}\n\n${dto.objective}\n\nGenerated by AVOS Code Factory.\n`,
      },
    ];

    if (dto.includeController !== false) {
      files.push({
        path: `${basePath}/${slug}.controller.ts`,
        type: "source",
        content: `import { Body, Controller, Post } from "@nestjs/common";\nimport { ${className}Request } from "./${slug}.contracts";\nimport { ${className}Service } from "./${slug}.service";\n\n@Controller("avos/capabilities/${slug}")\nexport class ${className}Controller {\n  constructor(private readonly service: ${className}Service) {}\n\n  @Post("execute")\n  execute(@Body() request: ${className}Request) {\n    return this.service.execute(request);\n  }\n}\n`,
      });
    }

    if (dto.includeTests !== false) {
      files.push({
        path: `${basePath}/${slug}.service.spec.ts`,
        type: "test",
        content: `import { ${className}Service } from "./${slug}.service";\n\ndescribe("${className}Service", () => {\n  it("executes the capability", () => {\n    const service = new ${className}Service();\n    const result = service.execute({ objective: "validate capability" });\n    expect(result.success).toBe(true);\n    expect(result.capability).toBe("${slug}");\n  });\n});\n`,
      });
    }

    return this.generation.generate({
      projectId: dto.projectId,
      name: dto.capabilityName,
      objective: dto.objective,
      language: "typescript",
      framework: "nestjs",
      metadata: {
        ...(dto.metadata ?? {}),
        capabilitySlug: slug,
        capabilityVersion: dto.version ?? "1.0.0",
        humanFinalAuthority: true,
      },
      files,
    });
  }

  private toSlug(value: string) {
    return value
      .trim()
      .replace(/([a-z0-9])([A-Z])/g, "$1-$2")
      .replace(/[^a-zA-Z0-9]+/g, "-")
      .replace(/^-+|-+$/g, "")
      .toLowerCase();
  }

  private toPascalCase(value: string) {
    return this.toSlug(value)
      .split("-")
      .filter(Boolean)
      .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
      .join("");
  }
}
