import { Injectable } from "@nestjs/common";
import { PrismaService } from "../prisma/prisma.service";

@Injectable()
export class AvosKernelService {
  constructor(private prisma: PrismaService) {}

  private clamp(value: number) {
    return Math.max(0, Math.min(100, Math.round(value)));
  }

  async decide(data: any) {
    const actions: string[] = [];

    if (data.event === "VehicleCreated" || data.entityType === "vehicle") {
      actions.push(
        "vehicle_valuation",
        "fraud_assessment",
        "trust_profile",
        "buyer_matching",
        "marketing_campaign",
        "export_opportunity_check"
      );
    } else {
      actions.push("log_only");
    }

    return (this.prisma as any).kernelDecision.create({
      data: {
        eventType: data.event || data.eventType,
        entityType: data.entityType || data.entity,
        entityId: data.entityId,
        decision: actions.includes("log_only") ? "log_only" : "execute_workflow",
        confidence: this.clamp(90),
        reason: "Kernel decision generated by AVOS Kernel.",
        actions,
        status: "approved",
      },
    });
  }

  list() {
    return (this.prisma as any).kernelDecision.findMany({
      orderBy: { createdAt: "desc" },
    });
  }
}
