import { Injectable } from "@nestjs/common";
import { createHash, randomUUID } from "node:crypto";
import { promises as fs } from "node:fs";
import { GenerationBlueprint, GeneratedFile, GenerationPackage, SupportedLanguage } from "../types/ultimate.types";
import { JsonFileStoreService } from "../infrastructure/json-file-store.service";

@Injectable()
export class UniversalGenerationService {
  constructor(private readonly store: JsonFileStoreService) {}
  async generate(input: Record<string, unknown>, materialize = false): Promise<GenerationPackage> {
    const blueprint = this.normalize(input); const files = this.render(blueprint);
    const pkg: GenerationPackage = { id:`package:${Date.now()}:${randomUUID()}`, blueprintId: blueprint.id!, name: blueprint.name, language:blueprint.language, framework:blueprint.framework, files, manifest:{ generator:"AVOS Universal Generation Platform", version:"CF-MP6.0.0", fileCount:files.length, humanFinalAuthority:true }, createdAt:new Date().toISOString() };
    await this.store.writeJson(this.store.path("packages", `${pkg.id}.json`), pkg);
    if (materialize) await this.materialize(pkg);
    return pkg;
  }
  async list(): Promise<GenerationPackage[]> { return this.store.listJson<GenerationPackage>(this.store.path("packages")); }
  async materialize(pkg: GenerationPackage): Promise<string> {
    const root = this.store.path("materialized", this.safe(pkg.name), pkg.id.replace(/[:]/g,"-"));
    for (const file of pkg.files) { const target = this.store.path("materialized", this.safe(pkg.name), pkg.id.replace(/[:]/g,"-"), file.relativePath); await fs.mkdir(require("node:path").dirname(target), {recursive:true}); await fs.writeFile(target,file.content,"utf8"); }
    return root;
  }
  supported(): Record<string, unknown> { return { languages:["typescript","python","dart","go","csharp"], frameworks:{typescript:["nestjs","node"],python:["fastapi","plain"],dart:["flutter","plain"],go:["net/http","plain"],csharp:["aspnetcore","plain"]}, contractDriven:true, deterministic:true }; }

  private normalize(input: Record<string, unknown>): GenerationBlueprint {
    const language = String(input.language ?? "typescript") as SupportedLanguage;
    if (!["typescript","python","dart","go","csharp"].includes(language)) throw new Error(`Unsupported language: ${language}`);
    return { id:String(input.id ?? `blueprint:${Date.now()}:${randomUUID()}`), name:String(input.name ?? "generated-service"), description:String(input.description ?? "Generated by AVOS Code Factory"), language, framework:String(input.framework ?? this.defaultFramework(language)), namespace:String(input.namespace ?? "Avos.Generated"), entities:Array.isArray(input.entities) ? input.entities as GenerationBlueprint["entities"] : [], endpoints:Array.isArray(input.endpoints) ? input.endpoints as GenerationBlueprint["endpoints"] : [], metadata:(input.metadata ?? {}) as Record<string,unknown> };
  }
  private render(b: GenerationBlueprint): GeneratedFile[] {
    const generated: Array<[string,string]> = b.language === "typescript" ? this.typescript(b) : b.language === "python" ? this.python(b) : b.language === "dart" ? this.dart(b) : b.language === "go" ? this.go(b) : this.csharp(b);
    return generated.map(([relativePath,content]) => ({relativePath,content,language:b.language,sha256:createHash("sha256").update(content).digest("hex")}));
  }
  private typescript(b: GenerationBlueprint): Array<[string,string]> { const cls=this.pascal(b.name); return [["src/main.ts",`import { NestFactory } from "@nestjs/core";\nimport { ${cls}Module } from "./${this.safe(b.name)}.module";\nasync function bootstrap(){ const app=await NestFactory.create(${cls}Module); await app.listen(process.env.PORT ?? 3000); }\nvoid bootstrap();\n`],[`src/${this.safe(b.name)}.module.ts`,`import { Module } from "@nestjs/common";\nimport { ${cls}Controller } from "./${this.safe(b.name)}.controller";\n@Module({controllers:[${cls}Controller]}) export class ${cls}Module {}\n`],[`src/${this.safe(b.name)}.controller.ts`,`import { Controller, Get } from "@nestjs/common";\n@Controller("${this.safe(b.name)}") export class ${cls}Controller { @Get("health") health(){ return {status:"ok", service:"${b.name}"}; } }\n`],["README.md",this.readme(b)]]; }
  private python(b: GenerationBlueprint): Array<[string,string]> { return [["app/main.py",`from fastapi import FastAPI\napp = FastAPI(title=${JSON.stringify(b.name)})\n@app.get("/health")\ndef health(): return {"status":"ok","service":${JSON.stringify(b.name)}}\n`],["requirements.txt","fastapi\nuvicorn\n"],["README.md",this.readme(b)]]; }
  private dart(b: GenerationBlueprint): Array<[string,string]> { return [["lib/main.dart",`import 'package:flutter/material.dart';\nvoid main()=>runApp(const App());\nclass App extends StatelessWidget{const App({super.key});@override Widget build(BuildContext context)=>MaterialApp(home:Scaffold(appBar:AppBar(title:const Text('${b.name}')),body:const Center(child:Text('AVOS generated application'))));}\n`],["README.md",this.readme(b)]]; }
  private go(b: GenerationBlueprint): Array<[string,string]> { return [["main.go",`package main\nimport ("encoding/json";"net/http")\nfunc main(){http.HandleFunc("/health",func(w http.ResponseWriter,r *http.Request){_ = json.NewEncoder(w).Encode(map[string]string{"status":"ok","service":"${b.name}"})});_ = http.ListenAndServe(":8080",nil)}\n`],["go.mod",`module avos.generated/${this.safe(b.name)}\n\ngo 1.22\n`],["README.md",this.readme(b)]]; }
  private csharp(b: GenerationBlueprint): Array<[string,string]> { return [["Program.cs",`var builder = WebApplication.CreateBuilder(args);\nvar app = builder.Build();\napp.MapGet("/health", () => new { status = "ok", service = "${b.name}" });\napp.Run();\n`],[`${this.pascal(b.name)}.csproj`,`<Project Sdk="Microsoft.NET.Sdk.Web"><PropertyGroup><TargetFramework>net8.0</TargetFramework><Nullable>enable</Nullable><ImplicitUsings>enable</ImplicitUsings></PropertyGroup></Project>\n`],["README.md",this.readme(b)]]; }
  private readme(b:GenerationBlueprint):string { return `# ${b.name}\n\n${b.description ?? ""}\n\nGenerated by AVOS Code Factory MP6. Human review is required before production release.\n`; }
  private safe(v:string):string { return v.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"") || "generated"; }
  private pascal(v:string):string { return v.split(/[^a-zA-Z0-9]/).filter(Boolean).map(x=>x.charAt(0).toUpperCase()+x.slice(1)).join("") || "Generated"; }
  private defaultFramework(l:SupportedLanguage):string { return ({typescript:"nestjs",python:"fastapi",dart:"flutter",go:"net/http",csharp:"aspnetcore"})[l]; }
}
