export const FLEET_ENTERPRISE_VERSION = "1.0.0";
export const DEFAULT_MAINTENANCE_INTERVAL_KM = 10000;
export const LOW_FUEL_THRESHOLD = 15;
export const HIGH_RISK_DRIVER_THRESHOLD = 45;
export const MAX_ACTIVE_TRIPS_PER_DRIVER = 1;
