export const CAPABILITY_ENTERPRISE_VERSION = "1.0.0";

export const CAPABILITY_ENTERPRISE_PILLARS = [
  "MULTI_TENANT_CAPABILITY_LAYER",
  "TENANT_CONFIGURATION",
  "TENANT_QUOTAS",
  "ENTERPRISE_GOVERNANCE",
  "HUMAN_APPROVAL_FRAMEWORK",
  "CAPABILITY_CERTIFICATION",
  "CAPABILITY_PUBLISHING",
  "MARKETPLACE_READINESS",
  "CAPABILITY_DISTRIBUTION",
  "CAPABILITY_AUDIT",
  "CAPABILITY_COMPLIANCE",
  "CAPABILITY_MIGRATION",
  "CAPABILITY_ARCHIVE",
  "POLICY_ENFORCEMENT",
  "ENTERPRISE_SDK_FOUNDATION",
  "PLUGIN_READINESS",
] as const;

export const CAPABILITY_CERTIFICATION_REQUIREMENTS = {
  FOUNDATION: { quality: 55, trust: 55, risk: 60 },
  STANDARD: { quality: 65, trust: 65, risk: 45 },
  ENTERPRISE: { quality: 75, trust: 75, risk: 30 },
  MISSION_CRITICAL: { quality: 85, trust: 85, risk: 20 },
} as const;