apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: avos-api
  namespace: avos-production
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: avos-api
  minReplicas: 3
  maxReplicas: 20
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 65
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70