import {
  AvosDesignSystemFoundation,
  DesignComponentDefinition,
  DesignToken,
} from "./design-system-foundation.types";

export const AVOS_DESIGN_TOKENS: DesignToken[] = [
  {
    name: "color.brand.primary",
    category: "COLOR",
    value: "#1D4ED8",
    description: "Primary AVOS brand action color",
  },
  {
    name: "color.brand.primarySoft",
    category: "COLOR",
    value: "#DBEAFE",
    description: "Soft brand background",
  },
  {
    name: "color.brand.accent",
    category: "COLOR",
    value: "#0F766E",
    description: "Intelligent mobility accent",
  },
  {
    name: "color.surface.canvas",
    category: "COLOR",
    value: "#F8FAFC",
    description: "Primary light canvas",
  },
  {
    name: "color.surface.card",
    category: "COLOR",
    value: "#FFFFFF",
    description: "Card and panel surface",
  },
  {
    name: "color.text.primary",
    category: "COLOR",
    value: "#0F172A",
    description: "Primary enterprise text",
  },
  {
    name: "color.text.secondary",
    category: "COLOR",
    value: "#475569",
    description: "Secondary text",
  },
  {
    name: "color.border.default",
    category: "COLOR",
    value: "#E2E8F0",
    description: "Default border",
  },
  {
    name: "color.status.success",
    category: "COLOR",
    value: "#15803D",
    description: "Success state",
  },
  {
    name: "color.status.warning",
    category: "COLOR",
    value: "#B45309",
    description: "Warning state",
  },
  {
    name: "color.status.danger",
    category: "COLOR",
    value: "#B91C1C",
    description: "Danger state",
  },
  {
    name: "font.family.primary",
    category: "TYPOGRAPHY",
    value: "Inter, Arial, sans-serif",
    description: "Primary Latin font family",
  },
  {
    name: "font.family.arabic",
    category: "TYPOGRAPHY",
    value: "Tajawal, Arial, sans-serif",
    description: "Primary Arabic font family",
  },
  {
    name: "font.size.caption",
    category: "TYPOGRAPHY",
    value: "12px",
    description: "Caption text",
  },
  {
    name: "font.size.body",
    category: "TYPOGRAPHY",
    value: "16px",
    description: "Body text",
  },
  {
    name: "font.size.title",
    category: "TYPOGRAPHY",
    value: "24px",
    description: "Section title",
  },
  {
    name: "font.size.display",
    category: "TYPOGRAPHY",
    value: "40px",
    description: "Display heading",
  },
  {
    name: "spacing.1",
    category: "SPACING",
    value: "4px",
    description: "Base spacing unit",
  },
  {
    name: "spacing.2",
    category: "SPACING",
    value: "8px",
    description: "Compact spacing",
  },
  {
    name: "spacing.3",
    category: "SPACING",
    value: "12px",
    description: "Small spacing",
  },
  {
    name: "spacing.4",
    category: "SPACING",
    value: "16px",
    description: "Default spacing",
  },
  {
    name: "spacing.6",
    category: "SPACING",
    value: "24px",
    description: "Section spacing",
  },
  {
    name: "spacing.8",
    category: "SPACING",
    value: "32px",
    description: "Large spacing",
  },
  {
    name: "radius.sm",
    category: "RADIUS",
    value: "8px",
    description: "Small control radius",
  },
  {
    name: "radius.md",
    category: "RADIUS",
    value: "14px",
    description: "Default component radius",
  },
  {
    name: "radius.lg",
    category: "RADIUS",
    value: "20px",
    description: "Card radius",
  },
  {
    name: "radius.pill",
    category: "RADIUS",
    value: "999px",
    description: "Pill radius",
  },
  {
    name: "shadow.card",
    category: "SHADOW",
    value: "0 8px 24px rgba(15, 23, 42, 0.08)",
    description: "Card elevation shadow",
  },
  {
    name: "motion.fast",
    category: "MOTION",
    value: "120ms",
    description: "Fast UI transition",
  },
  {
    name: "motion.normal",
    category: "MOTION",
    value: "220ms",
    description: "Default UI transition",
  },
  {
    name: "breakpoint.mobile",
    category: "BREAKPOINT",
    value: "640px",
    description: "Mobile breakpoint",
  },
  {
    name: "breakpoint.tablet",
    category: "BREAKPOINT",
    value: "1024px",
    description: "Tablet breakpoint",
  },
  {
    name: "breakpoint.desktop",
    category: "BREAKPOINT",
    value: "1280px",
    description: "Desktop breakpoint",
  },
];

export const AVOS_DESIGN_COMPONENTS: DesignComponentDefinition[] = [
  {
    name: "AvosButton",
    category: "ACTION",
    accessibilityRequired: true,
    responsiveRequired: true,
    states: ["default", "hover", "focus", "disabled", "loading"],
  },
  {
    name: "AvosCard",
    category: "LAYOUT",
    accessibilityRequired: true,
    responsiveRequired: true,
    states: ["default", "interactive", "selected"],
  },
  {
    name: "AvosInput",
    category: "INPUT",
    accessibilityRequired: true,
    responsiveRequired: true,
    states: ["default", "focus", "error", "disabled"],
  },
  {
    name: "AvosBadge",
    category: "FEEDBACK",
    accessibilityRequired: true,
    responsiveRequired: true,
    states: ["neutral", "success", "warning", "danger", "info"],
  },
  {
    name: "AvosPageHeader",
    category: "NAVIGATION",
    accessibilityRequired: true,
    responsiveRequired: true,
    states: ["default"],
  },
  {
    name: "AvosMetricCard",
    category: "DATA",
    accessibilityRequired: true,
    responsiveRequired: true,
    states: ["default", "positive", "negative", "attention"],
  },
];

export const AVOS_DESIGN_SYSTEM: AvosDesignSystemFoundation = {
  version: "1.0.0",
  status: "OFFICIAL",
  brandName: "AVOS Enterprise",
  tagline: "The Operating System for Mobility",
  themeStrategy: "LIGHT_FIRST",
  bilingualReady: true,
  accessibilityStandard: "WCAG 2.2 AA",
  tokens: AVOS_DESIGN_TOKENS,
  components: AVOS_DESIGN_COMPONENTS,
  governanceRules: [
    "All AVOS interfaces must consume official design tokens",
    "Light theme is the default AVOS experience",
    "All components must support keyboard and screen-reader access",
    "All product interfaces must support responsive layouts",
    "Arabic and English layouts must be supported",
    "Product teams may extend tokens but may not silently replace official tokens",
    "Industry packs must use shared components before creating custom variants",
  ],
};