export type PlatformSection = {
  route: string;
  title: string;
  category: string;
  description: string;
  featured: boolean;
};

export const platformSections: PlatformSection[] = [
  { route: "/enterprise-command-center", title: "Enterprise Command Center", category: "Executive", description: "مركز القيادة المؤسسي الموحد.", featured: true },
  { route: "/applications/executive-dashboard", title: "Executive Dashboard", category: "Executive", description: "لوحة الإدارة التنفيذية ومؤشرات المنصة.", featured: true },
  { route: "/enterprise-factory-v3", title: "AVOS Factory", category: "Factory", description: "مصنع المنصة وتوليد القدرات والمنتجات.", featured: true },
  { route: "/foundation-command-center", title: "Foundation Command Center", category: "Foundation", description: "مراقبة أسس AVOS وحالتها التشغيلية.", featured: true },
  { route: "/compliance-governance-center", title: "Compliance & Governance", category: "Governance", description: "الحوكمة والامتثال والسلطة البشرية النهائية.", featured: true },
  { route: "/innovation-lab-center", title: "Innovation Lab", category: "Innovation", description: "إدارة الأفكار والابتكار والتجارب.", featured: true },
  { route: "/ai-command-center", title: "AI Command Center", category: "Intelligence", description: "مركز قيادة الذكاء الاصطناعي ومحركات القرار.", featured: true },
  { route: "/knowledge-intelligence-center", title: "Knowledge Intelligence", category: "Knowledge", description: "المعرفة والذاكرة والبحث المؤسسي.", featured: true },
  { route: "/marketplace-ai", title: "Marketplace AI", category: "Marketplace", description: "السوق الذكي والفرص والتوصيات التجارية.", featured: true },
  { route: "/vehicles", title: "Vehicles", category: "Mobility", description: "إدارة المركبات والبحث والمقارنة.", featured: true },
  { route: "/global-operations-center", title: "Global Operations", category: "Operations", description: "العمليات العالمية والتوسع والمتابعة.", featured: true },
  { route: "/enterprise-workspace", title: "Enterprise Workspace", category: "Workspace", description: "مساحة العمل الموحدة لإدارة عمليات AVOS.", featured: true },
  { route: "/codegen-runtime-engines", title: "Codegen Runtime Engines", category: "Factory", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/enterprise-factory-v1", title: "Enterprise Factory V1", category: "Factory", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/enterprise-factory-v2", title: "Enterprise Factory V2", category: "Factory", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/genesis-core-v1", title: "Genesis Core V1", category: "Factory", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/genesis-enterprise-v1", title: "Genesis Enterprise V1", category: "Factory", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/genesis-runtime-v1", title: "Genesis Runtime V1", category: "Factory", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/industry-factory", title: "Industry Factory", category: "Factory", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/pack-builder-v3", title: "Pack Builder V3", category: "Factory", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/ai-governance-platform", title: "Ai Governance Platform", category: "Foundation", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/architecture-compliance-platform", title: "Architecture Compliance Platform", category: "Foundation", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/architecture-registry-foundation", title: "Architecture Registry Foundation", category: "Foundation", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/brand-foundation", title: "Brand Foundation", category: "Foundation", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/constitutional-foundation", title: "Constitutional Foundation", category: "Foundation", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/core-foundation-stack", title: "Core Foundation Stack", category: "Foundation", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/design-system-foundation", title: "Design System Foundation", category: "Foundation", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/enterprise-foundations", title: "Enterprise Foundations", category: "Foundation", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/explainability-trust-platform", title: "Explainability Trust Platform", category: "Foundation", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/foundation-core", title: "Foundation Core", category: "Foundation", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/foundation-governance", title: "Foundation Governance", category: "Foundation", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/foundation-governance-conformance", title: "Foundation Governance Conformance", category: "Foundation", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/industry-governance-partners", title: "Industry Governance Partners", category: "Foundation", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/reference-architecture", title: "Reference Architecture", category: "Foundation", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/service-compliance-safety", title: "Service Compliance Safety", category: "Foundation", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/strategic-foundation", title: "Strategic Foundation", category: "Foundation", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/agriculture-agritech-industry", title: "Agriculture Agritech Industry", category: "Industries", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/aviation-industry", title: "Aviation Industry", category: "Industries", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/banking-fintech-industry", title: "Banking Fintech Industry", category: "Industries", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/education-industry", title: "Education Industry", category: "Industries", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/energy-utilities-industry", title: "Energy Utilities Industry", category: "Industries", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/environment-waste-industry", title: "Environment Waste Industry", category: "Industries", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/food-beverage-industry", title: "Food Beverage Industry", category: "Industries", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/government-public-sector-industry", title: "Government Public Sector Industry", category: "Industries", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/heavy-equipment-industry", title: "Heavy Equipment Industry", category: "Industries", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/hospitality-tourism-industry", title: "Hospitality Tourism Industry", category: "Industries", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/industry-expansion", title: "Industry Expansion", category: "Industries", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/industry-mega-bundle-1", title: "Industry Mega Bundle 1", category: "Industries", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/industry-mega-bundle-2", title: "Industry Mega Bundle 2", category: "Industries", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/industry-mega-bundle-3", title: "Industry Mega Bundle 3", category: "Industries", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/industry-operations", title: "Industry Operations", category: "Industries", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/industry-pack-integration", title: "Industry Pack Integration", category: "Industries", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/industry-platform", title: "Industry Platform", category: "Industries", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/industry-services-ecosystem", title: "Industry Services Ecosystem", category: "Industries", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/insurance-industry-platform", title: "Insurance Industry Platform", category: "Industries", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/legal-professional-services-industry", title: "Legal Professional Services Industry", category: "Industries", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/maritime-industry", title: "Maritime Industry", category: "Industries", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/media-entertainment-industry", title: "Media Entertainment Industry", category: "Industries", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/mining-resources-industry", title: "Mining Resources Industry", category: "Industries", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/nonprofit-humanitarian-industry", title: "Nonprofit Humanitarian Industry", category: "Industries", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/security-emergency-services-industry", title: "Security Emergency Services Industry", category: "Industries", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/space-satellite-industry", title: "Space Satellite Industry", category: "Industries", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/sports-events-industry", title: "Sports Events Industry", category: "Industries", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/telecommunications-industry", title: "Telecommunications Industry", category: "Industries", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/universal-industry-core", title: "Universal Industry Core", category: "Industries", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/ai-growth-center", title: "Ai Growth Center", category: "Intelligence", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/capacity-demand-intelligence", title: "Capacity Demand Intelligence", category: "Intelligence", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/enterprise-commerce-intelligence-g3", title: "Enterprise Commerce Intelligence G3", category: "Intelligence", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/enterprise-customer-intelligence-g4", title: "Enterprise Customer Intelligence G4", category: "Intelligence", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/enterprise-finance-intelligence-g5", title: "Enterprise Finance Intelligence G5", category: "Intelligence", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/enterprise-intelligence-layer", title: "Enterprise Intelligence Layer", category: "Intelligence", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/enterprise-knowledge-academy", title: "Enterprise Knowledge Academy", category: "Intelligence", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/enterprise-knowledge-memory-g7", title: "Enterprise Knowledge Memory G7", category: "Intelligence", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/executive-strategy-center", title: "Executive Strategy Center", category: "Intelligence", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/global-intelligence-platform", title: "Global Intelligence Platform", category: "Intelligence", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/industry-intelligence-finance", title: "Industry Intelligence Finance", category: "Intelligence", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/knowledge-academy-command", title: "Knowledge Academy Command", category: "Intelligence", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/loyalty-membership-intelligence", title: "Loyalty Membership Intelligence", category: "Intelligence", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/revenue-margin-intelligence", title: "Revenue Margin Intelligence", category: "Intelligence", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/service-ai-copilot", title: "Service Ai Copilot", category: "Intelligence", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/service-marketplace-intelligence", title: "Service Marketplace Intelligence", category: "Intelligence", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/sovereign-intelligence-center", title: "Sovereign Intelligence Center", category: "Intelligence", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/strategic-planning-center", title: "Strategic Planning Center", category: "Intelligence", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/ultimate-strategy-platform", title: "Ultimate Strategy Platform", category: "Intelligence", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/adaptive-growth-studio", title: "Adaptive Growth Studio", category: "Marketplace", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/commerce-notifications", title: "Commerce Notifications", category: "Marketplace", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/applications/customer-app", title: "Customer App", category: "Marketplace", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/customer-experience", title: "Customer Experience", category: "Marketplace", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/customer-experience-command", title: "Customer Experience Command", category: "Marketplace", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/customer-value-retention", title: "Customer Value Retention", category: "Marketplace", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/enterprise-ecosystem-marketplace-g9", title: "Enterprise Ecosystem Marketplace G9", category: "Marketplace", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/enterprise-innovation-growth-g8", title: "Enterprise Innovation Growth G8", category: "Marketplace", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/growth-revenue-expansion", title: "Growth Revenue Expansion", category: "Marketplace", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/industry-commerce-revenue", title: "Industry Commerce Revenue", category: "Marketplace", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/industry-customer-growth", title: "Industry Customer Growth", category: "Marketplace", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/marketplace-execution", title: "Marketplace Execution", category: "Marketplace", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/retail-commerce-industry", title: "Retail Commerce Industry", category: "Marketplace", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/revenue-commerce", title: "Revenue Commerce", category: "Marketplace", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/service-customer-lifecycle", title: "Service Customer Lifecycle", category: "Marketplace", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/service-partner-growth", title: "Service Partner Growth", category: "Marketplace", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/service-pricing-revenue", title: "Service Pricing Revenue", category: "Marketplace", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/auction", title: "Auction", category: "Mobility", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/auctions", title: "Auctions", category: "Mobility", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/automotive-industry", title: "Automotive Industry", category: "Mobility", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/vehicles/compare", title: "Compare", category: "Mobility", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/dealer", title: "Dealer", category: "Mobility", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/applications/dealer-app", title: "Dealer App", category: "Mobility", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/global-mobility", title: "Global Mobility", category: "Mobility", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/seller/inventory", title: "Inventory", category: "Mobility", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/seller/leads", title: "Leads", category: "Mobility", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/live-auctions", title: "Live Auctions", category: "Mobility", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/seller/listings/new", title: "New", category: "Mobility", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/parts", title: "Parts", category: "Mobility", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/rentals", title: "Rentals", category: "Mobility", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/seller", title: "Seller", category: "Mobility", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/service-parts-supply", title: "Service Parts Supply", category: "Mobility", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/autonomous-operations-center", title: "Autonomous Operations Center", category: "Operations", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/enterprise-global-operations-g2", title: "Enterprise Global Operations G2", category: "Operations", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/enterprise-resilience-command", title: "Enterprise Resilience Command", category: "Operations", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/enterprise-risk-resilience-g6", title: "Enterprise Risk Resilience G6", category: "Operations", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/incident-response-center", title: "Incident Response Center", category: "Operations", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/recovery-resilience-center", title: "Recovery Resilience Center", category: "Operations", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/resilience-laboratory", title: "Resilience Laboratory", category: "Operations", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/security-threat-center", title: "Security Threat Center", category: "Operations", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/service-automation-center", title: "Service Automation Center", category: "Operations", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/service-capacity-dispatch", title: "Service Capacity Dispatch", category: "Operations", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/service-contracts-sla", title: "Service Contracts Sla", category: "Operations", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/service-executive-command", title: "Service Executive Command", category: "Operations", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/service-fleet-operations", title: "Service Fleet Operations", category: "Operations", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/service-health-observability", title: "Service Health Observability", category: "Operations", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/service-operations", title: "Service Operations", category: "Operations", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/service-provider-performance", title: "Service Provider Performance", category: "Operations", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/service-quality", title: "Service Quality", category: "Operations", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/service-risk-resilience", title: "Service Risk Resilience", category: "Operations", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/service-workforce", title: "Service Workforce", category: "Operations", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/services", title: "Services", category: "Operations", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/unified-business-operations", title: "Unified Business Operations", category: "Operations", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/account", title: "Account", category: "Platform", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/ads", title: "Ads", category: "Platform", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/autonomous-enterprise-execution", title: "Autonomous Enterprise Execution", category: "Platform", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/autonomous-enterprise-os", title: "Autonomous Enterprise Os", category: "Platform", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/account/bookings", title: "Bookings", category: "Platform", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/change-configuration-center", title: "Change Configuration Center", category: "Platform", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/commercial-launch", title: "Commercial Launch", category: "Platform", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/commercial-launch-readiness", title: "Commercial Launch Readiness", category: "Platform", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/continuous-evolution-sovereignty", title: "Continuous Evolution Sovereignty", category: "Platform", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/design-experience-platform", title: "Design Experience Platform", category: "Platform", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/digital-twin-command", title: "Digital Twin Command", category: "Platform", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/ecosystem-economy-center", title: "Ecosystem Economy Center", category: "Platform", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/ecosystem-platform", title: "Ecosystem Platform", category: "Platform", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/enterprise-coach-center", title: "Enterprise Coach Center", category: "Platform", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/enterprise-digital-twin", title: "Enterprise Digital Twin", category: "Platform", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/enterprise-ecosystem", title: "Enterprise Ecosystem", category: "Platform", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/enterprise-federation-platform", title: "Enterprise Federation Platform", category: "Platform", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/enterprise-metadata-platform", title: "Enterprise Metadata Platform", category: "Platform", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/enterprise-platform-standards", title: "Enterprise Platform Standards", category: "Platform", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/enterprise-platform-ultimate", title: "Enterprise Platform Ultimate", category: "Platform", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/enterprise-product-suites", title: "Enterprise Product Suites", category: "Platform", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/enterprise-settings", title: "Enterprise Settings", category: "Platform", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/enterprise-ultimate-f1", title: "Enterprise Ultimate F1", category: "Platform", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/enterprise-ultimate-f2", title: "Enterprise Ultimate F2", category: "Platform", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/enterprise-ultimate-f3", title: "Enterprise Ultimate F3", category: "Platform", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/enterprise-ultimate-f5", title: "Enterprise Ultimate F5", category: "Platform", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/enterprise-ultimate-f6", title: "Enterprise Ultimate F6", category: "Platform", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/enterprise-ultimate-g1", title: "Enterprise Ultimate G1", category: "Platform", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/export", title: "Export", category: "Platform", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/export-shipping", title: "Export Shipping", category: "Platform", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/favorites", title: "Favorites", category: "Platform", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/finance", title: "Finance", category: "Platform", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/finance-cockpit", title: "Finance Cockpit", category: "Platform", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/global-enterprise-platform", title: "Global Enterprise Platform", category: "Platform", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/global-scale-ultra", title: "Global Scale Ultra", category: "Platform", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/global-standards-observatory", title: "Global Standards Observatory", category: "Platform", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/grand-business-product", title: "Grand Business Product", category: "Platform", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/hyper-runtime-platform", title: "Hyper Runtime Platform", category: "Platform", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/innovation-venture-lab", title: "Innovation Venture Lab", category: "Platform", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/insurance", title: "Insurance", category: "Platform", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/launch-readiness", title: "Launch Readiness", category: "Platform", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/legacy-modernization-command", title: "Legacy Modernization Command", category: "Platform", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/maps", title: "Maps", category: "Platform", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/market-expansion-center", title: "Market Expansion Center", category: "Platform", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/account/messages", title: "Messages", category: "Platform", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/messages", title: "Messages", category: "Platform", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/notifications", title: "Notifications", category: "Platform", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/account/offers", title: "Offers", category: "Platform", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/partner-ecosystem-center", title: "Partner Ecosystem Center", category: "Platform", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/payments", title: "Payments", category: "Platform", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/plates", title: "Plates", category: "Platform", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/priority-focus-center", title: "Priority Focus Center", category: "Platform", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/profile", title: "Profile", category: "Platform", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/providers", title: "Providers", category: "Platform", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/release-deployment-center", title: "Release Deployment Center", category: "Platform", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/account/saved", title: "Saved", category: "Platform", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/search", title: "Search", category: "Platform", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/sell", title: "Sell", category: "Platform", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/strategic-planner-command", title: "Strategic Planner Command", category: "Platform", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/sustainability-impact-center", title: "Sustainability Impact Center", category: "Platform", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/transaction-lifecycle", title: "Transaction Lifecycle", category: "Platform", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/ultimate-platform-completion", title: "Ultimate Platform Completion", category: "Platform", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/universal-data-fabric", title: "Universal Data Fabric", category: "Platform", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/universal-sdk-center", title: "Universal Sdk Center", category: "Platform", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/user-role-experience", title: "User Role Experience", category: "Platform", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/workforce-talent-center", title: "Workforce Talent Center", category: "Platform", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/workshops", title: "Workshops", category: "Platform", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/applications/admin-console", title: "Admin Console", category: "Workspace", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/applications", title: "Applications", category: "Workspace", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/provider-workspace/bookings", title: "Bookings", category: "Workspace", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/dashboard", title: "Dashboard", category: "Workspace", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/dashboard-widgets", title: "Dashboard Widgets", category: "Workspace", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/enterprise-autonomous-executive-g10", title: "Enterprise Autonomous Executive G10", category: "Workspace", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/applications/finance-partner-app", title: "Finance Partner App", category: "Workspace", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/applications/insurance-partner-app", title: "Insurance Partner App", category: "Workspace", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/applications/logistics-app", title: "Logistics App", category: "Workspace", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/provider-workspace", title: "Provider Workspace", category: "Workspace", description: "قسم متاح ضمن منصة AVOS.", featured: false },
  { route: "/applications/workshop-app", title: "Workshop App", category: "Workspace", description: "قسم متاح ضمن منصة AVOS.", featured: false },
];

export const featuredPlatformSections = platformSections.filter(
  (section) => section.featured,
);

export const platformCategories = Array.from(
  new Set(platformSections.map((section) => section.category)),
).sort();
