import { Injectable } from "@nestjs/common";
import { randomUUID } from "crypto";
import { ProjectGenerationPlan, ProjectGeneratorRequest } from "./project-generator.contracts";
import { ProjectKindRegistryService } from "./project-kind-registry.service";

@Injectable()
export class ProjectGenerationPlannerService {
  constructor(private readonly kinds: ProjectKindRegistryService) {}

  createPlan(request: ProjectGeneratorRequest, requiresHumanApproval: boolean): ProjectGenerationPlan {
    const requestId = request.id ?? randomUUID();
    const projectSlug = this.toSlug(request.name);
    const projectClassName = this.toClassName(request.name);
    const namespace = request.namespace?.trim() || "avos.generated";
    const variables: Record<string, unknown> = {
      projectName: request.name,
      projectSlug,
      projectClassName,
      namespace,
      description: request.description ?? "Generated by AVOS Factory.",
      humanFinalAuthority: true,
      ...(request.variables ?? {})
    };
    const definition = this.kinds.resolve(request.kind);
    const approved = !requiresHumanApproval ||
      (request.humanApproved === true && Boolean(request.approvedBy));

    return {
      id: randomUUID(),
      requestId,
      name: request.name,
      projectId: `${namespace}.${projectSlug}`,
      kind: request.kind,
      status: requiresHumanApproval && !approved ? "awaiting-approval" : "approved",
      outputPath: request.outputPath ?? projectSlug,
      requestedBy: request.requestedBy,
      approvedBy: approved ? request.approvedBy : undefined,
      humanApproved: approved,
      requiresHumanApproval,
      createdAt: new Date().toISOString(),
      structure: definition.structureFactory(request, variables),
      variables,
      warnings: requiresHumanApproval && !approved
        ? ["Project generation requires Human Final Authority approval."]
        : []
    };
  }

  private toSlug(value: string): string {
    return value.trim().replace(/([a-z0-9])([A-Z])/g, "$1-$2")
      .replace(/[^A-Za-z0-9]+/g, "-").replace(/^-+|-+$/g, "").toLowerCase() || "generated-project";
  }

  private toClassName(value: string): string {
    return value.trim().replace(/([a-z0-9])([A-Z])/g, "$1 $2")
      .split(/[^A-Za-z0-9]+/).filter(Boolean)
      .map((word) => word.charAt(0).toUpperCase() + word.slice(1)).join("") || "GeneratedProject";
  }
}
