export const GLOBAL_LANGUAGE_PLATFORM_VERSION = "1.0.0";
export const DEFAULT_LANGUAGE_CODE = "ar";
export const DEFAULT_FALLBACK_LANGUAGE_CODE = "en";
export const DEFAULT_TRANSLATION_QUALITY_THRESHOLD = 85;
export const SUPPORTED_DIRECTIONS = ["LTR", "RTL"];
